### ISSUE TITLE
Pos Order Criando duas faturas

### ISSUE THREAD

**Issue by rodriguesraphael** [Trust-Code/odoo-brasil#107]
Ao validar uma venda no Ponto de Venda ele gera duas invoices.
Numero Fatura "1"
Numero Fatura "INV/2017/0018"

Se puderem me ajudar a encontrar o que poderia ser.
Estou tentando criar a NFC-e apartir do ponto de venda, mas ainda não localizei o que poderia estar causando isto.

**Comment by rodriguesraphael** [comment]
A função para criar a invoice esta desta forma:
foo = self._prepare_edoc_vals(res)
eletronic = self.env['invoice.eletronic'].create(foo)
eletronic.action_post_validate()
return res

**Comment by danimaribeiro** [comment]
Manda um print com o que você considera duas faturas.

**Comment by rodriguesraphael** [comment]
![faturas odoo](https://cloud.githubusercontent.com/assets/20387443/22927712/9923d8e4-f291-11e6-9d8d-4fdbaefc2a46.png)
![invoice eletronic](https://cloud.githubusercontent.com/assets/20387443/22927711/9923c0b6-f291-11e6-99df-3f52fc27ae3f.png)

**Comment by rodriguesraphael** [comment]
Nas Faturas foi criada uma única, 'INV/2017/0024'.
Porém em Invoices Eletronic são criadas duas invoices, uma derivada desta fatura mencionada e uma invoice sem nenhuma account invoice relacionada(no print são as duas últimas da imagem).

A eletronic invoice é criada no POS BR, 
foo = self._prepare_edoc_vals(res)
eletronic = self.env['invoice.eletronic'].create(foo)
eletronic.action_post_validate()

E o process order do POS cria a outra fatura apartir do account invoice.

return res
