### ISSUE TITLE
Erro ao realizar pagamento de fatura no módulo Faturamento (odoo 14)

### ISSUE THREAD

**Issue by telmob** [Trust-Code/odoo-brasil#1093]
Ao clicar no botão de 'PAGAR' em uma linha de fatura no módulo de Faturamento, recebo o erro abaixo:

`Erro de Acesso`
`Você não tem permissão para acessar registros 'Assistente Para Lançamento de Pagamentos' (payment.account.move.line).
Atualmente nenhum grupo permite esta operação.
Entre em contato com seu administrador para solicitar acesso se necessário`

Acontece na versão 14 do odoo, mesmo com usuário com permissões totais de admin.

**Comment by fabioluna** [comment]
Corrigido pelo PR #1109

**Comment by telmob** [comment]
Excelente. Obrigado!
