### ISSUE TITLE
Botão "Pagar" no Contas a Pagar e Receber do módulo de faturamento não está disponível (Odoo 14)

### ISSUE THREAD

**Issue by marceloengecom** [Trust-Code/odoo-brasil#1099]
![odoo-PagarFatura](https://user-images.githubusercontent.com/7999196/121454936-0ca0f400-c97a-11eb-86bc-503dbcbe0256.png)

Caso eu clique no botão "Receber", me aparece a seguinte mensagem:

Você não tem permissão para acessar registros 'Assistente Para Lançamento de Pagamentos' (payment.account.move.line).
Atualmente nenhum grupo permite esta operação.
Entre em contato com seu administrador para solicitar acesso se necessário

**Comment by kaoecoito** [comment]
Só complementando que além da questão da permissão desse Wizard ele também não esta funcionando, vai dar erro em action_confirm_payment, pois na model account.payment não existe mais a propriedade move_line_ids, pelo que vi ele existia na versão 13.
Tentei dar uma olhada para ver o que mudou mas ainda não conheço o suficiente do Odoo para ajustar essa parte de pagamento do código!

**Comment by marceloengecom** [comment]
Com a última atualização do repositório foi ajustado o problema. Obrigado!
