### ISSUE TITLE
Lendo arquivo de Retorno do Itau.

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#110]
Não sei se o objetivo é fazer por aqui mesmo (Importar Extrato, Forçar Formato): 
Se sim, mudando algumas linhas no br_bank_statement_import,  consegui fazer o Itau funcionar, mudei o nome de alguns campos, 
e comentei algumas coisas, se for este o objetivo posso acertar o código e enviar um pr: 
    
    def _parse_cnab(self, data_file, raise_error=False):
        cnab240_file = tempfile.NamedTemporaryFile()
        cnab240_file.write(data_file)
        cnab240_file.flush()
        # Aqui estava Sicoob -> Itau
        arquivo = Arquivo(itau, arquivo=open(cnab240_file.name, 'r'))
        transacoes = []
        for lote in arquivo.lotes:
            import pudb;pu.db
            for evento in lote.eventos:
                #if banco_impt == u'itau_cobranca_240':
                if evento.servico_codigo_movimento not in (6,8,9,10):
                    continue
                valor = evento.valor_titulo
                #if evento.tipo_lancamento == 'D':
                #    valor *= -1
                transacoes.append({
                    'name': evento.numero_documento,
                    'date': datetime.strptime(
                        str(evento.data_credito), '%d%m%Y'),
                    'amount': valor,
                    'partner_name': evento.sacado_nome,
                    'ref': evento.nosso_numero,
                    'unique_import_id': str(evento.numero_documento)[:6],
                })
        header = arquivo.lotes[0].header
        trailer = arquivo.lotes[0].trailer

        inicio = datetime.strptime(str(header.data_credito), '%d%m%Y')
        final = datetime.strptime(str(header.data_credito), '%d%m%Y')

        vals_bank_statement = {
            'name': u"%s - %s até %s" % (
                arquivo.header.nome_do_banco,
                inicio.strftime('%d/%m/%Y'),
                final.strftime('%d/%m/%Y')),
            'date': inicio,
            #'balance_start': arquivo.lotes[0].header.valor_saldo_inicial,
            #'balance_end_real': arquivo.lotes[0].trailer.valor_saldo_final,
            'transactions': transacoes
        }

**Comment by danimaribeiro** [comment]
Tem o arquivo de testes para eu poder testar aqui, eu não entendi porque você comentou algumas coisas.
Outra coisa, para o Odoo mostrar o item correto se faz necessário implementar este código aqui na 10. Dai ele já traz todos os itens corretos no extrato é só clicar em conciliar.
https://github.com/Trust-Code/odoo-brazil-banking/blob/ea6bd73418ad92cdc6335d696213ec04e5727fde/l10n_br_cnab_import/models/account_bank_statement.py

**Comment by crsilveira** [comment]
Estas linhas, pq não é um extrato, não tenho saldo ini nem final ... por isso a primeira pergunta se é este o local pra fazer isso .
[B413027A.TXT](https://github.com/Trust-Code/odoo-brasil/files/784024/B413027A.TXT)

**Comment by danimaribeiro** [comment]
Eu estou em dúvidas, porque se a empresa quer usar a importação de extrato bancário e importar o cnab, vai acabar que vai ter lançamentos no extrato referente ao cnab que já foram conciliados.
Se for usar só o extrato, a maioria lança uma linha só no extrato com o total que caiu na conta aquele dia de boletos, dai fica ruim para achar todos os boletos ao que aquilo pertence.

Dai eu não sei qual a melhor forma de resolver este problema?

**Comment by crsilveira** [comment]
Entendi, eu acho q tem q ter as duas opções, a linha do extrato  no caso do recebimento do boleto não dá pra ser usada ,pois, não vai baixar os títulos, o CNAB fará isso, e todas as baixas feita pelo CNAB representa uma linha no extrato, quando for feito via CNAB esta linha do extrato deverá ser "descartada" , infelizmente não tenho o OFX da empresa ainda pra ver o q acontece , após, a baixa do cnab com a linha do extrato, mas terei em breve.

**Comment by danimaribeiro** [comment]
Se imaginarmos um boleto de 100 e dai um extrato com o boleto de 100 + um pagamento de 50 via deposito.

Ao importar o cnab o Odoo vai registrar um extrato e o saldo final vai ser 100, ao importar o OFX vai ter mais os 100 e os 50, resultando em um valor final de 250.

Algum deles teríamos que descartar e ainda ajustar os valores iniciais e finais. Agora será que da pra fazer de forma automática?

**Comment by crsilveira** [comment]
Neste caso de apenas um boleto, sem problema, não precisaria do CNAB agora , acima de 1 acho ele mais útil, pois, já identifica os "títulos" recebidos ...

**Comment by danimaribeiro** [comment]
Eu lembrei como tinha feito na 8.0.
Eu buscava o valor do último extrato, e dai o valor final é este valor mais a soma dos itens.

**Comment by crsilveira** [comment]
dai sim, perfeito.

**Comment by marciorpbradoo** [comment]
Saudações!
Estou subir o arquivo CNAB 240 no ambiente de homologação do Itaú Empresas, porém ele não está sendo aceito. Analisando o arquivo .REM gerado, notei que alguns campos como o "boleto_cnab_code" estão causando problemas pois comparei o arquivo gerado com o manual do Itaú e novos digitos que não seguem o padrão utilizado pelo Itaú estão sendo adicionados.
Essa funcionalidade está ok, alguém já fez o teste de upload de .REM para o Itaú ?

**Comment by crsilveira** [comment]
Eu utilizo o Itau, mas houve mudanças no projeto depois disso , vou ver o q está diferente e já informo.

**Comment by marciorpbradoo** [comment]
Fico no aguardo, obrigado!

**Comment by crsilveira** [comment]
Fiz apenas uma correcao no febraban/cnab_240/cnab240.py: 

        if self.order.payment_mode_id.boleto_cnab_code:
            cedente_convenio = self.order.payment_mode_id.boleto_cnab_code
        return {
       ...
       'cedente_convenio': cedente_convenio,

E gerou o arquivo sem erro.

**Comment by danimaribeiro** [comment]
Consegue enviar um PR com essas melhorias?
