### ISSUE TITLE
Fatura não tem mais campo para desconto (Odoo14)

### ISSUE THREAD

**Issue by marceloengecom** [Trust-Code/odoo-brasil#1100]
Ao criar uma fatura para cliente, não temos mais o campo desconto.

**Comment by fabioluna** [comment]
Alguns campos, a partir da versão 13 do Odoo, tem uma opção de serem escondidos na tela.
https://github.com/odoo/odoo/blob/7be2e136c5e7a62d440f8323f36076d486976825/addons/account/views/account_move_views.xml#L767

Para fazer estes campos aparecerem, no fim do header do grid tem um botão com 3 pontos, é só clicar nele e habilitar para mostrar o campo.

**Comment by marceloengecom** [comment]
Obrigado Fábio!
Na verdade eu esqueci de habilitar a opção "Desconto nas linhas" nas configurações do usuário. Eu vi isso somente hoje.

Abraço.
