### ISSUE TITLE
odoo 13 - Relatórios de contabilidade "balancete, balanço patrimonial " não encontrados, estes items foram retirados?

### ISSUE THREAD

**Issue by gilsonlima10** [Trust-Code/odoo-brasil#1103]
Não encontro muitos relatorios, que existem na versão 11 e não existe nas versões posteriores.

**Comment by fabioluna** [comment]
A Odoo removeu estes relatórios da versão community a partir do Odoo 12. A melhor opção pra gerar estes relatórios hoje é o mis_builder da OCA.
