### ISSUE TITLE
Erro ao terminar processo de importação de NFe - Odoo14

### ISSUE THREAD

**Issue by rodmad85** [Trust-Code/odoo-brasil#1104]
Boa tarde a todos, após realizar toda a instalação de todos os módulos disponíveis para Odoo 14 da Trust Code, não consigo importar as NFe's por completo para gerar a fatura. As NF's estão sendo sincronizadas normalmente na SEFAZ porém ocorre este erro ao tentar terminar a importação por completo. Estou utilizando a ultima atualização do Odoo e da TrustCode.

Odoo Server ErrorTraceback (most recent call last): File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch result = request.dispatch() File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch result = self._call_function(**self.params) File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function return checked_call(self.db, *args, **kwargs) File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper return f(dbname, *args, **kwargs) File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call result = self.endpoint(*a, **kw) File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__ return self.method(*args, **kw) File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap response = f(*args, **kw) File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button action = self._call_kw(model, method, args, kwargs) File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw result = _call_kw_multi(method, model, args, kwargs) File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi result = method(recs, *args, **kwargs) File "/usr/lib/python3/dist-packages/odoo/addons/odoo-brasil/l10n_br_nfe_import/models/eletronic_document.py", line 1065, in generate_account_move account_invoice = self.env['account.move'].create(vals) File "<decorator-gen-206>", line 2, in create File "/usr/lib/python3/dist-packages/odoo/api.py", line 344, in _model_create_multi return create(self, [arg]) File "/usr/lib/python3/dist-packages/odoo/addons/purchase/models/account_invoice.py", line 102, in create moves = super(AccountMove, self).create(vals_list) File "<decorator-gen-173>", line 2, in create File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi return create(self, arg) File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 1851, in create vals_list = self._move_autocomplete_invoice_lines_create(vals_list) File "/usr/lib/python3/dist-packages/odoo/addons/account/models/account_move.py", line 1808, in _move_autocomplete_invoice_lines_create move = self_ctx.new(vals) File "/usr/lib/python3/dist-packages/odoo/models.py", line 5506, in new record._update_cache(values, validate=False) File "/usr/lib/python3/dist-packages/odoo/models.py", line 5148, in _update_cache raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name)) 

Exception The above exception was the direct cause of the following exception: 

Traceback (most recent call last): File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception raise exception.with_traceback(None) from new_cause ValueError: Invalid field 'type' on model 'account.move'

**Comment by fabioluna** [comment]
Este errro foi corrigido pelos PRs #1139 e #1140
