### ISSUE TITLE
O Código liberado para emissão da NFC é imprestavel não funciona..enrrolação

### ISSUE THREAD

**Issue by gilsonlima10** [Trust-Code/odoo-brasil#1122]
O Código liberado para emissão da NFC é imprestavel não funciona..enrrolação
Odoo 11, 13, 14.
A distribuição Odoo Brasil não PODE SER CONSIDERADO PROGRAMA LIVRE, POIS O CODIGO É IMPRESTAVEL

**Comment by fabioluna** [comment]
Não acredito que este tipo de comentário seja útil do ponto de vista de comunidade em qualquer repositório open source, pois existem várias pessoas que gastam seu tempo desenvolvendo trabalhos e nem sempre recebem para isto. Tendo dito isto, existem empresas utilizando a NFC-e nas versões 11, 12 e 13, sendo a versão 12 a mais utilizada. Provavelmente você deve estar com algum erro de configuração, mas com certeza não é assim que você conseguirá ajuda.

**Comment by gilsonlima10** [comment]
a versão 12 esta com um BUG, após uma instalação nova e instalação da localização brasileira, não cria um banco de dados novo ..... não acredito em comunidade ( e sim em panelinha) ..isso não é correto, vocês usam um programa maravilhoso desenvolvido pela odoo SA , se aproveitam DAS VANTAGENS de trabalhar com programa livre, ganham muito e liberam um codigo com suporte zero e provavelmente sem funcionar!! não é correto...não aceito...irei encher a caixa de correio da odoo SA com o objetivo de mudar estas posturas de vocês!!!

**Comment by gilsonlima10** [comment]
se querem gerar um programa de caixinha..que o façam , mas tirem o status de PROGRAMA LIVRE...e abram mão das VANTAGENS que o mesmo oderecem!!!

**Comment by danimaribeiro** [comment]
Isso aqui nao eh rede social para você fazer desabafo ou reclamação.
Se tem um bug abre um issue, senão fica quieto.
