### ISSUE TITLE
Erro ao usar account_cancell para cancelamento de faturas com módulo de contabilidade simplicado instalado

### ISSUE THREAD

**Issue by deyvsonaguiar** [Trust-Code/odoo-brasil#117]
Prezado Danimar e amigos da Trustcode,

Solicito ajuda para esse erro que percebo depois de instalar a account_cancell para cancelar faturas já contabilizadas no sistema. 
- Após instalar o account-cancell nao sei onde fica, em português para habilitar "all cancelling entries" pois tem muitos tutoriais em inglês mas não acho em português esse menu. Sabem onde fica?
- Tem alguma incompatibilidade do br_coa da Trustcode e esse módulo? Então o que fazer para habilitar o cancelamento de faturas, preciso excluir lançamento errados. 

obs.: já desinstalei como o Danimar pediu, o módulo de contabilidade brasileira que vem padrão no odoo. Só tenho módulos Trust-code. 

obrigado pelo espaço.

**Comment by mstuttgart** [comment]
@deyvsonaguiar no cadastro diário que você usou na fatura que deseja cancelar, tem um checkbox que quando marcado, permite você cancelar a fatura.

**Comment by deyvsonaguiar** [comment]
@mstuttgart vc pode me contactar pra eu tirar outras dúvidas? Creio que seja experiente no odoo. Meu contato de email: deyvsonaguiar@gmail.com ficarei no aguardo. 
E sobre o diário, não achei vou te mandar um print de uma fatura aberta:
http://pt-br.tinypic.com/view.php?pic=2ywcry0&s=9

**Comment by danimaribeiro** [comment]
Contabilidade -> Configuração -> Diários

Habilitar o modo desenvolvedor antes.

**Comment by deyvsonaguiar** [comment]
Boa Danimar, muito obrigado viu. Só umas considerações:  o caminho que percorri foi Configurações->Ativar modo desenvolvedor -> Contabilidade -> Configurações /Contabilidade/Diários e finalmente tinha lá escondido. Obrigado mais uma vez pela dica. 
Enviei um email pela central de atendimento do site sobre possíveis treinamento e consultoria que a Truscode poderia me fornecer. Gostaria de um feedback. Vou ficar no aguardo! Abraços!
