### ISSUE TITLE
erro ao clicar em cotações

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#120]
File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column sale_order_line.icms_st_aliquota_deducao does not exist
LINE 1: ..." as "pis_rule_id","sale_order_line"."id" as "id","sale_orde...

**Comment by danimaribeiro** [comment]
Atualizar o módulo br_sale e/ou br_account.
