### ISSUE TITLE
Como atualizar os modulos odoo-brasil

### ISSUE THREAD

**Issue by lindenbergp** [Trust-Code/odoo-brasil#123]
Alguém sabe de que maneira faço para atualizar os modulos de minha instalação. Fiz uma nova instalação e vi que varias novas alterações. Mas não consigo exportar o banco de dados para nova instalação e nem atualizar a instalação existente (odoo 10)

**Comment by danimaribeiro** [comment]
Da uma olhada na documentação.
https://www.odoo.com/documentation/10.0/reference/cmdline.html
