### ISSUE TITLE
Classificação Fiscal (NCM) não salva

### ISSUE THREAD

**Issue by izaguerreiro** [Trust-Code/odoo-brasil#126]
Ao salvar o NCM, o registro é salvo, porém não é listado na lista de NCMs.
Isso é um bug ou seria alguma configuração errada?

**Comment by danimaribeiro** [comment]
Não consegui reproduzir o bug.

**Comment by izaguerreiro** [comment]
Vou tentar gravar aqui e te mando.

**Comment by izaguerreiro** [comment]
Posso te enviar o video por e-mail? Se sim, qual e-mail posso enviar.
