### ISSUE TITLE
Duvida quanto a retenção de impostos NFS-e

### ISSUE THREAD

**Issue by mstuttgart** [Trust-Code/odoo-brasil#133]
Bom tarde pessoal.

Gostaria de saber qual o nível de desenvolvimento da localização referente a retenção de impostos da nota fiscal de serviço. Ainda não foi desenvolvido nada ou já existe algo em desenvolvimento?

Obrigado!

**Comment by yannickbh** [comment]
Olá Michel!
Atualmente a localização já atende a retenção de impostos na fonte da NF de serviço. Nós fizemos apenas alguma melhorias para obter os impostos do serviço selecionado de forma automática.
As regras que aplicamos são muito similares ao apresentado neste artigo: http://suporte.agilize.com.br/hc/pt-br/articles/204799855-Reten%C3%A7%C3%A3o-na-fonte-Como-funciona-
Basicamente, o mais importante é entender o código de serviço e configurar os impostos dos serviços de acordo a regulamentação do mesmo, para que estes últimos sejam retidos de maneira correta.
abs,

**Comment by mstuttgart** [comment]
Obrigado @yannickbh
