### ISSUE TITLE
Erro ao validar fatura

### ISSUE THREAD

**Issue by izaguerreiro** [Trust-Code/odoo-brasil#136]
Ao tentar validar uma fatura, ocorreu o erro abaixo:
(Eu não sei se é alguma configuração que eu não fiz ou um erro mesmo)
![captura de tela de 2017-03-22 16-43-14](https://cloud.githubusercontent.com/assets/2241504/24217540/f3ee5d40-0f1e-11e7-9ce8-071849f3fcdc.png)
![captura de tela de 2017-03-22 16-43-22](https://cloud.githubusercontent.com/assets/2241504/24217541/f3f289ba-0f1e-11e7-854b-764d7a5fe281.png)

**Comment by danimaribeiro** [comment]
Uma atualização do módulo br_account deve resolver.
