### ISSUE TITLE
Erro campo inexistente

### ISSUE THREAD

**Issue by izaguerreiro** [Trust-Code/odoo-brasil#138]
Atualizei os módulos odoo-brasil, e agora ao tentar acessar as ordens de venda ocorre o erro da imagem abaixo. 
Existe algum comando que atualiza o banco de daos automáticamente tipo no django (./manage.py migrate) ou teria que criar o campo no banco de dados manualmente?

![captura de tela de 2017-03-23 09-15-24](https://cloud.githubusercontent.com/assets/2241504/24248659/0951f77e-0faf-11e7-885a-e1a09789a643.png)
![captura de tela de 2017-03-23 09-15-30](https://cloud.githubusercontent.com/assets/2241504/24248658/094f8958-0faf-11e7-8d1c-944696569fa1.png)

**Comment by danimaribeiro** [comment]
https://www.odoo.com/documentation/10.0/reference/cmdline.html

**Comment by izaguerreiro** [comment]
Quando eu executo `./odoo-conf -d odoo -r odoo -u "all"` acontece esse erro:

psycopg2.operationalerror fatal peer authentication failed for user odoo

Estou pesquisando na internet, mas ainda não encontrei a solução, poderia me ajudar por favor?

**Comment by danimaribeiro** [comment]
Você deve passar também o caminho do arquivo de configuração, senão o odoo não sabe os parametros do banco de dados.

Recentemente foi adicionado o módulo account_cancel como dependencia do br_account, se faz necessário instalar ele também.

**Comment by lindenbergp** [comment]
No codigo citado pela izaguerreiro (./odoo-conf -d odoo -r odoo -u "all"), onde adiciono o caminho do banco de dados?

**Comment by danimaribeiro** [comment]
./odoo-bin --config=odoo-config

Use --config ou -c
