### ISSUE TITLE
erro ao clicar no menu contabilidade/contabilidade/impostos

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#142]
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 461, in raise_view_error
    raise ValueError(message)
ValueError: O campo `percent_credit` n\xe3o existe

Contexto de erro:
Veja `account.tax.form`
[view_id: 378, xml_id: account.view_tax_form, model: account.tax, parent_id: n/a]

**Comment by danimaribeiro** [comment]
Desinstale o módulo simples nacional e atualize seu código.
