### ISSUE TITLE
erro ao emitir boleto bradesco

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#147]
invalid literal for int() with base 10: '/': (<type 'exceptions.ValueError'>, ValueError("invalid literal for int() with base 10: '/'",), <traceback object at 0x7f137512a290>)

**Comment by Rynaro** [comment]
@ewertonmagalhaes, poderia enviar todo o trace do erro? Pelo que eu vi esse é o trace parcial do que ocorreu.
Se puder, detalhe os passos que fez para criarmos um caso de teste bem próximo ao seu comportamento.

**Comment by crsilveira** [comment]
O número da fatura gerada está com   "/"  ?

**Comment by ewertonmagalhaes** [comment]
eu atualizei todos o módulos; Emiti uma fatura a um determinado cliente, gerei a nfe e a mesma foi autenticada. Agora quando em gerar boleto aparece

Odoo Aviso - Aviso
Error
Não é possível gerar os boletos
Certifique-se que a fatura esteja confirmada e o
forma de pagamento seja duplicatas: None

o "modo de pagamento" está como boleto e a espécie  do título como duplicata mercantil.  O código do convênio também está preenchido.

**Comment by ewertonmagalhaes** [comment]
srs,

fiz nova implantação de uma base desde o zero, e novamente deu o mesmo erro ao clicar no ícone de gerar boleto

Odoo Aviso - Aviso
'bool' object has no attribute 'encode': (<type 'exceptions.AttributeError'>, AttributeError("'bool' object has no attribute 'encode'",), <traceback object at 0x7f37323ff5a8>)

alguém pode me dar uma luz?

**Comment by danimaribeiro** [comment]
É algum campo que está faltando preencher no cadastro.

**Comment by ewertonmagalhaes** [comment]
refiz tudo pela quinta vez, agora está dando este erro
BoletoBradesco.campo_livre must have a length of 25, not u'66170900000000000000200034650' (len: 29): (<type 'exceptions.ValueError'>, ValueError("BoletoBradesco.campo_livre must have a length of 25, not u'66170900000000000000200034650' (len: 29)",), <traceback object at 0x7f1959f523f8>)

**Comment by ewertonmagalhaes** [comment]
encontrado erro, o sequencial "nosso numero" para o bradesco deve ser numérico e no máximo 11 dígitos, para o banco do brasil somente 10 dígitos

**Comment by danimaribeiro** [comment]
Conseguiu resolver o seu problema?
