### ISSUE TITLE
10% para garçom no POS

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#15]
gostaria de solicitar a opção de incluir 10% no total da conta do POS pois é fundamental para venda de sistemas para bares e restaurantes

**Comment by danimaribeiro** [comment]
O recurso já existe.
![gorjetaas](https://cloud.githubusercontent.com/assets/854781/21047840/494da700-bdf3-11e6-8609-38198e8fda11.png)
