### ISSUE TITLE
multiempresas

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#159]
existe um bug no relatório de contas a pagar. Quando se cria uma segunda empresa (multiempresa) no relatório de contas a receber continua vinculado à primeira empresa. Veja no exemplo abaixo, a fatura inv/fat/034 foi emitida pela empresa plasdias (mostrado corretamente na fatura de cliente) ja no relatório de contas a receber aparece vinculado à primeira empresa cadastrada "termoplastic" (errado)

![image](https://cloud.githubusercontent.com/assets/20585325/25431006/26a3ff0a-2a55-11e7-9ff0-79f280c3339c.png)

![image](https://cloud.githubusercontent.com/assets/20585325/25431026/3b960160-2a55-11e7-9dfe-cda2aab903d4.png)

**Comment by danimaribeiro** [comment]
Acredito que este bug deva ser reportado no https://github.com/odoo/odoo
Não tem código na localização que modifica isto.
