### ISSUE TITLE
Erro De emissão de NFS-e 1206 (Assinatura Digital do RPS incorreta)

### ISSUE THREAD

**Issue by DiogoBerti** [Trust-Code/odoo-brasil#161]
Boa tarde!

Estou com um problema para emitir um Nota fiscal de serviços.
Ao validar o invoice (que também cria um edoc), a nota segue o fluxo normal para emissão, e consigo enviar para emissão na prefeitura. Mas recebo o seguinte erro:

```
Situação: 1206
Mensagem: Assinatura Digital do RPS incorreta - String verificada (533500491 00000000102820170502TNN00000000012023400000000000000002798201773463000159)
Código Verificação:
```
Alguém já chegou à este erro?
No meu caso, apenas um Invoice está dando este problema, todos os outros seguem normalmente para a emissão.
Testei em diferentes cenários e com diferentes produtos (mas sempre usando os mesmo parametros) e consegui emitir a nota com sucesso, mas nesse caso em específico eu não consigo passar desse erro.

Agradeço desde já pela ajuda.
Se precisarem de alguma informação extra basta me perguntar.

Att,
Diogo Berti.

**Comment by danimaribeiro** [comment]
Este erro já foi corrigido há um tempo atrás.
https://github.com/Trust-Code/odoo-brasil/commit/3b109f03a9578e3ac03a3214b988de8365c9cb49#diff-7d43fb8f3f0636728a8b5b6412fda740

**Comment by DiogoBerti** [comment]
Ok!

Obrigado Danimar!
