### ISSUE TITLE
erro ao emitir nota fiscal

### ISSUE THREAD

**Issue by thiago95macedo** [Trust-Code/odoo-brasil#17]
Situação: 215
Mensagem: cvc-complex-type.2.4.a: Invalid content was found starting with element 'cEAN'. One of '{"http://www.portalfiscal.inf.br/nfe":xProd}' is expected.
![nfe_erro](https://cloud.githubusercontent.com/assets/14120712/21072282/35d406ec-be93-11e6-9267-c92bacb8ff05.png)

**Comment by danimaribeiro** [comment]
É necessário adicionar o xml da nfe.

**Comment by thiago95macedo** [comment]
Fiqui meio que sem entender Danimar, adicionar onde? Como?
Ele jã não gerou a XML?
![nfe_erro](https://cloud.githubusercontent.com/assets/14120712/21074835/1969a2b4-bed9-11e6-8ec0-ccfb8894a4e7.png)

**Comment by danimaribeiro** [comment]
Adicionar o xml aqui.

**Comment by thiago95macedo** [comment]
Aqui?

**Comment by Mackilem** [comment]
Boa tarde,

Isso mesmo meu amigo.... anexa o xml que está com erro aqui na conversa que
assim podemos analisar o que houve.

abraço

Em seg, 12 de dez de 2016 às 16:12, Thiago Macêdo <notifications@github.com>
escreveu:

**Comment by danimaribeiro** [comment]
Vou fechar este issue, se ainda estiver acontecendo nos envie o xml que reabro o issue.
