### ISSUE TITLE
Importação do XML da NFe

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#170]
Vi um branch com a importação do XML , ele parece bastante diferente do anterior, não será feito mais da forma que era o anterior, importar o xml para o pedido de compras ??

**Comment by danimaribeiro** [comment]
A importação do xml vai ser exclusivamente para gerar a fatura.
Caso exista pedido de compra o mesmo será validado com a fatura, mas não faz sentido a importação gerar pedido de compra.

**Comment by crsilveira** [comment]
Trabalho com empresas pequenas, poucas utilizam pedido de compras , ou melhor só utilizam pra dar entrada na Nota, e alimentar o Estoque. Grato pela resposta, vou fazer um módulo pra fazer desta forma.
