### ISSUE TITLE
Erro na geração nfe quando o campo "Referência interna" contém espaços

### ISSUE THREAD

**Issue by carlos-korovsky** [Trust-Code/odoo-brasil#173]
Quando o campo "Referência Interna" de um produto contém espaços ocorre um erro na validação da nota fiscal eletrônica.
Passos para reprodução:
1o. Criar um novo produto, preenchendo corretamente todos os campos.
2o. Ao preencher o campo "Referência interna" acrescentar um espaço ao final do código.
3o. Preencher uma fatura e emitir a nota fiscal de produto.
Obs. Não foi testado quando contém espaços no meio do código ou no seu início.

**Comment by danimaribeiro** [comment]
Todos os campos que são utilizados na NFe tem este "problema".
Não está nos planos validar um a um.

Um PR no sentido de validar a NFe via schema seria a melhor solução.

**Comment by danimaribeiro** [comment]
Não será corrigido este.
