### ISSUE TITLE
Erro no arredondamento da NFe

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#175]
Tentando fazer uma NFe com 2 produtos : 
Produto 1 - Qtde = 6, Preço = 18,333333 Total = 110,00
Produto 2 - Qtde = 6, Preço = 18,333333 Total = 110,00

Mesmo mudando as casas decimais para  6 unidades, tinha erro : 
Valor do Produto difere do produto valor unitario de tributacao e quantidade tributavel

Só consegui passar a nota alterando : 
   'vUnCom': "%.06f" % item.preco_unitario,
   'vUnTrib': "%.06f" % item.preco_unitario,

Linhas : 253 e 258 de : br_nfe/models/invoice_eletronic.py

fazendo isso consegui gerar esta nf.

**Comment by danimaribeiro** [comment]
Acho que o melhor seria a serialização respeitar o número de casas configurado no Odoo.
Buscar a precisão decimal utilizado no account.invoice, e utilizar o mesmo para gerar a formatação.

Um PR nesse sentido seria legal :+1:

**Comment by danimaribeiro** [comment]
Foram feitas umas melhorias nesse sentido, acredito que o erro não ocorra mais.
