### ISSUE TITLE
Erro durante criação da fatura -  Mensagens Documento Eletrônico

### ISSUE THREAD

**Issue by carlos-korovsky** [Trust-Code/odoo-brasil#176]
Procedimento:
  1 - Criar uma nova fatura e adicionar itens (produtos);
  2 - Verificar a lista de Mensagens do Documento Eletrônico (está populada com as mensagens definidas na regra de posição fiscal).
  3 - Salvar a fatura;
  4 - A lista de Mensagens do Documento Eletrônico é limpa. 
Após estes procedimentos, será necessário editar novamente a fatura para incluir manualmente as mensagens.

**Comment by danimaribeiro** [comment]
Não consegui identificar o problema.
Mas tem algo relacionado com este problema:
https://github.com/odoo/odoo/issues/15419

Na epóca antes de resolver isto, o problema também acontecia.
Tentei usar git bisect para identificar o problema novamente, mas não obtive sucesso.

**Comment by carlos-korovsky** [comment]
Olá Danimar, desculpe a demora para lhe responder. Não é gerada nenhuma excessão, acredito que seja alguma coisa relacionada com o método para criar uma nova fatura (write se não me engano) que não está incluindo os valores desta lista na hora de salvar a lista de mensagens.

**Comment by danimaribeiro** [comment]
Não será corrigido a nível de localização, talvez a Odoo lance algum patch para o código voltar a funcionar.
