### ISSUE TITLE
Nosso número alterando ao reajusta a data de vencimento do boleto

### ISSUE THREAD

**Issue by Rynaro** [Trust-Code/odoo-brasil#177]
Em alguns diálogos com a agência que estava integrando o Odoo com o pagamento via boleto, mencionaram que um boleto poderia ter seu vencimento alterado e reenviado em um novo arquivo de remessa, atualizando o registro de nosso número já registrado anteriormente no sistema do banco.
Porém, hoje o módulo de reimpressão e reajuste de vencimento do boleto, ativa a flag `boleto_emitido`, e isso força o Odoo gerar um novo nosso número ao arquivo de remessa. 
Aos olhos do banco, o boleto anterior ainda consta em espera de pagamento, e um novo é criado. Forçando o cancelamento manual do nosso número anterior no sistema do banco, para evitar boletos duplicados.

Este procedimento é de conhecimento padrão do Odoo?

**Comment by danimaribeiro** [comment]
É isto mesmo.
Porém tem bancos que este procedimento de reenvio não existe.

**Comment by Rynaro** [comment]
A cooperativa Sicoob permite o reenvio de boletos com alteração de data de vencimento, alocando-o em outro arquivo de remessa. E ao chegar no sistema deles, a leitura da linha é feita, e o registro anterior toma conta do anterior.
Aliás, esse foi o procedimento passado pela equipe responsável da agência a ser integrada.

**Comment by danimaribeiro** [comment]
Quando eu implementei sicoob eu pedi se existia esta opção, me falaram que ainda não tinha.
Devem ter atualizado.

**Comment by Rynaro** [comment]
Em conversa com o pessoal da Sicoob, eles disponibilizam um sistema padrão de reimpressão de boletos com vencimento no dia, onde o sistema deles por si só se atualiza.
Eu criei um sistemas de tarefa agendada, que ao entender que o boleto atingiu seu vencimento (no caso Sicoob), ele gera um e-mail redirecionando esse link, e dando as informações necessárias ao usuário sobre como reimprimir o boleto com o novo vencimento. (No caso passando o código da agência, e o nosso número com digito verificador)
Isso é uma ótima saída que vi, mas como se trata de uma tarefa automatizada para minha regra de negócio, não sei se seria viável acoplar ao core odoo-brasil. Mas deixo aqui documentado a solução que elaborei como saída.

**Comment by danimaribeiro** [comment]
Para a versão 11 serão feitas melhorias neste sentido.
Porém pode ficar a vontade para enviar melhorias para esta versão.
