### ISSUE TITLE
Atualização do br_purchase, gerando erro na valorização do inventário.

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#183]
Aplicando a atualização,  Cálculo correto do custo de compra do produto levando em conta impost… 
no br_purchase, a valorização do inventário, fica louca, não consegui entender pq , mas exemplo:
produtox , qtde = 10 , preço unitário 90 , o valor do inventário fica R$ 9.000,00 e não R$ 900,00 como seria o correto.

Estou procurando se encontrar o motivo , posto aqui.

**Comment by crsilveira** [comment]
def _get_stock_move_price_unit(self):
    aqui esta retornando o valor total como preco, no exempro acima , retorna : R$ 900  e não 90

**Comment by crsilveira** [comment]
Deixando a função assim, resolve: 
    
    # Calcula o custo da mercadoria comprada
    @api.multi
    def _get_stock_move_price_unit(self):
        price = self.price_unit
        ctx = self._prepare_tax_context()
        tax_ids = self.taxes_id.with_context(**ctx)
        taxes = tax_ids.compute_all(
            price, self.order_id.currency_id,
            self.product_qty, product=self.product_id,
            partner=self.order_id.partner_id)

        price = taxes['total_included']

        for tax in taxes['taxes']:
            # Quando o imposto não tem conta contábil, deduzimos que ele não é
            # recuperável e portanto somamos ao custo, como partimos do valor
            # já com imposto se existir conta diminuimos o valor deste imposto
            if tax['account_id']:
                price -= tax['amount']
       # ACRESCENTEI AQUI.
        price = price / self.product_qty

        return price

**Comment by danimaribeiro** [comment]
Consegue enviar um PR?

**Comment by crsilveira** [comment]
Posso mandar, eu só não sei se está é a forma correta de resolver ...
