### ISSUE TITLE
No module named pytrustnfe.nfe

### ISSUE THREAD

**Issue by alcaporal** [Trust-Code/odoo-brasil#184]
Instalei a locaização. Mas na hora de instalar os aplicativos gera esse erro:
O módulo "br_base" não pode ser instalado porque uma dependência externa não foi encontrada: No module named pytrustnfe.nfe

O detalhe é que Pytrustnfe já está instalado normalmente com o comando
pip install pytrustnfe

Também já reiniciei o server e atualizei os módulos para conferir.

**Comment by danimaribeiro** [comment]
http://www.trustcode.com.br/forum/ajuda-1/question/no-module-named-pytrustnfe-nfe-2

**Comment by danimaribeiro** [comment]
Você pode rodar este comando no terminal para ver se foi instalado corretamente:

python -c "import pytrustnfe.nfe"
