### ISSUE TITLE
Erro ao instalar módulo "teste" br_point_sale

### ISSUE THREAD

**Issue by SantosDLeandro** [Trust-Code/odoo-brasil#185]
Quando realizo a compra e efetivo o pagamento logo apos o fechamento apresenta este erro. 
Relatório de Erros do Odoo - Ponto de Venda
[erro_nfc-e_odoo_trust.txt](https://github.com/Trust-Code/odoo-brasil/files/1204696/erro_nfc-e_odoo_trust.txt)

**Comment by danimaribeiro** [comment]
Apesar de o módulo ainda não estar finalizado, este erro você corrige configurando a série padrão no cadastro de ponto de venda.
