### ISSUE TITLE
Baixa CNAB Sicoob não vincula conta de recebimento, com conta bancária

### ISSUE THREAD

**Issue by Rynaro** [Trust-Code/odoo-brasil#187]
Ao importar arquivo CNAB para a baixa de faturas, alguns boletos vinculam o pagamento bancário a conta de recebimento, dando baixa na fatura, e na conta a receber.
Porém, fora identificado que em algumas situações a linha de baixa do banco é identificada, porém a conta de recebimento não consegue ser vinculada, forçando o usuário a "excluir a linha azul" e informar uma contrapartida manual forçando a conta.

**Comment by danimaribeiro** [comment]
Quais os passos para reproduzir?

**Comment by Rynaro** [comment]
Primeiramente, com o arquivo de retorno cnab você deve importar ele no _Importar Extrato_, feito isso, o Odoo vai computar as linhas a serem reconciliadas com a baixa do arquivo. De fato, alguns arquivos são identificados sem problema algum, porém, há casos que a linha da conta do banco não "bate" com a linha da contrapartida, as vezes até sendo mostrado outro cliente abaixo da linha lida.
Não consegui ver um padrão lógico para que isso ocorra, há por vezes, que o arquivo lido não apresenta quaisquer problemas, e o mesmo baixa todas as linhas informadas, mas por outras que algumas linhas não conseguem gerar contrapartida. 
A linha "azul" tem os dizeres no ícone de informação; *Pagamento registrado, porém não conciliado*

Acredito que essa issue tenha mais vinculo a branch `importar-cnabs`, ou `importar-cnab-sicoob`

---
_Nota: As vezes a linha "de baixo", da linha lida do cnab, nem bate com o documento informado, trazendo até mesmo outro parceiro para ela._

**Comment by danimaribeiro** [comment]
Vou fechar este issue, infelizmente não tenho como as etapas para reproduzir.
E também o ideal é que seja feito o teste na branch 10.0 sempre.
