### ISSUE TITLE
Ação bloqueada Boleto Itáu

### ISSUE THREAD

**Issue by gvicentes** [Trust-Code/odoo-brasil#189]
Olá
Estamos fazendo alguns testes com a cobrança por boleto e ao validar a fatura como pagamento por boleto apresenta o seguinte aviso:

"Ação Bloqueada!
Para prosseguir é necessário preencher os seguintes campos:
Numeração da fatura deve ser menor que 12 caracteres quando usado boleto"

![erro_validar-fatura](https://user-images.githubusercontent.com/30909677/29189266-4f3970ea-7dec-11e7-9737-9c1beecf3764.JPG)

Não encontrei onde seja configurado no boleto essa situação da numeração da fatura.

**Comment by Rynaro** [comment]
Acredito que o **Código Abreviado** de seu diário de recebimento esteja superando o limite de 2 caracteres.
Experimente ir no diário referenciado e verificar a quantidade de caracteres que há nele. E experimente ajustar para o uso de 2 caracteres de tamanho, caso ele ultrapasse esse limite.

**Comment by gvicentes** [comment]
Olá, obrigado por responder.
Verifiquei que após configurado o boleto foi adicionado no meu diário uma entrada tipo Banco, em que o Código Abreviado era BNK2 e alterei para BI. Mesmo assim a fatura não valida. 

![diario_boleto](https://user-images.githubusercontent.com/30909677/29215384-370307d0-7e81-11e7-8112-0807c39a62f8.JPG)
Seria essa a modificação proposta? 

Saberia me informar quais a informações coletadas para a geração do número do documento no boleto, seria tipo: nº da cotação + nº da fatura? (ex. SO009INV/2017/0014)
Desculpe o excesso de perguntas e que para mim ainda não está muito claro o funcionamento da cobrança por boleto no odoo. Obrigado mais uma vez.

**Comment by Rynaro** [comment]
Quando eu tive esse problema, fora por conta do diário tipo _Venda_ que o Odoo precisou que eu configurasse para operar juntamente com o diário do banco, onde eu gero entradas no diário de venda, e também no diário do banco em contrapartidas.
A minha alteração foi em relação ao diário de **venda**, onde minha linha de cotação fica com ele modelo, por exemplo: DV/2017/0153

**Comment by gvicentes** [comment]
Era isso mesmo, criei uma nova entrada tipo venda no diário com o código abreviado NF e fiz o mapeamento da posição fiscal de venda para esse novo diário, com isso consegui validar a fatura e consequentemente gerar o boleto.
Agora estou com um erro para gerar o arquivo de remessa, vou abrir um novo Issue sobre isso...
Muito obrigado, Henrique!

**Comment by danimaribeiro** [comment]
Quando são dúvidas, pode ser usado o fórum em vez de criar um issue aqui no github.

**Comment by danimaribeiro** [comment]
Link:
https://www.trustcode.com.br/forum/ajuda-1
