### ISSUE TITLE
Nota de Devolução de Compras

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#197]
Fazendo uma nota de Devolução de Compras, usando Pedido de Compras / Fatura de Fornecedor, o sistema coloca o Tipo NF = Entrada, neste Caso deveria ser Devolução, se fizer por Vendas ... vai ficar tudo certo, mas seria o correto ?? Obrigatoriamente teria q marcar o fornecedor como Cliente pra Fazer isso ...

**Comment by danimaribeiro** [comment]
Tipo da NF só tem Entrada ou Saída.

Um devolução de compras você clica em "Reembolso" na fatura de fornecedor que você cadastrou inicialmente.

**Comment by Gesimieloliveira** [comment]
E quando for fazer um Retorno de Mercadoria de Comodato usando o CFOP 5909, como fazer?
