### ISSUE TITLE
Bloquear a criação direta de lançamento de contas a pagar e receber.

### ISSUE THREAD

**Issue by sandrofolk** [Trust-Code/odoo-brasil#2]
Versão 10.0 Branch 10.
Passo a passo:
Acessar menu "Contabilidade / Receber e Pagar / Contas a receber/pagar / botão criar"

Problema encontrado:
Por uma questão de fluxo de processo essa opção de criar um lançamento direto não deve ser feito!

Objetivo esperado:
Deveria haver um bloqueio desse botão ou algo assim!

**Comment by danimaribeiro** [comment]
Fixed https://github.com/Trust-Code/odoo-brasil/commit/42b3b41f55e13d8e7daaf564192716561b18b7fe
