### ISSUE TITLE
Rotina de envio de comando/movimentação de baixa de boletos CNAB

### ISSUE THREAD

**Issue by Rynaro** [Trust-Code/odoo-brasil#220]
Após o envio de um nosso número válido pelo arquivo CNAB 240 ao banco, ele se registra normalmente. Porém, em um caso hipotético onde o boleto foi erroneamente gerado, seja qual for o motivo, lendo o código fonte, não abordei nenhuma rotina que envia um comando de baixa automática do mesmo.
Gostaria de saber se há esta funcionalidade no pacote **odoo-brasil**, ou se está no *roadmap* de desenvolvimento.
Caso não, acho interessante colocar este assunto nesta issue, para analisarmos o melhor modo de construir esta feature. E que ficarei feliz em contribuir. :smiley: 

---
Exemplo: No Sicoob se você informar a informação 02 na posição de movimentação, ele aciona o comando de baixa automática quando o CNAB for lido pelo sistema deles.

**Comment by danimaribeiro** [comment]
Está no roadmap para desenvolvimento na versão 11.
Mas você pode ficar a vontade para contribuir.

Existem dois casos, um em que a ordem de cobrança está no estado provisório, neste caso apenas deletar a linha da ordem correspondente resolve o problema.

Quando a ordem de cobrança já foi gerada, deve-se gerar uma linha nova com a movimentação correspondente cancelando o movimento.

Vai ser necessário um pouco de refactoring aqui:
https://github.com/Trust-Code/odoo-brasil/blob/10.0/br_boleto/models/account_move_line.py#L27
e aqui:
https://github.com/Trust-Code/odoo-brasil/blob/10.0/br_cnab/febraban/cnab_240/cnab_240.py#L127

Sempre pensando em não quebrar funcionalidade existente.

**Comment by Rynaro** [comment]
Para essa funcionalidade seria interessante criar um "impedimento" de uso do marcador que permite cancelamento de faturas no diário específico quando há modo de pagamento por boleto. Pois, quando o cancelamento de fatura ocorre, as referências das linhas de recebimento são perdidas com **unlink**. Assim impossibilitando a linha de cobrança de ser gerada, pela falta de uma linha de movimento vinculada.

Foi um caso que analisei, já que no setor que fazem o procedimento as vezes os usuários usam a opção de _cancelar fatura_. Não sei você tem uma ideia diferente da minha para lidar com esse tipo de situação, @danimaribeiro

**Comment by danimaribeiro** [comment]
Neste caso do cancelamento, deve ser gerada uma nova linha na ordem de cobrança para cancelar o boleto. Todos os dados devem ser copiados para a linha antes do item do diário ser deletado.

**Comment by Rynaro** [comment]
Uma dúvida pontual referente a esta linha:
https://github.com/Trust-Code/odoo-brasil/blob/10.0/br_cnab/febraban/cnab_240/cnab_240.py#L231

Qual o real intuito de estar puxando um campo `monetary` representando o valor do título, esse campo não é equivalente ao _debit_ (da linha do movimento), ou _value_ (da linha da ordem de cobrança) que são `float` de precisão de 2 ?

**Comment by danimaribeiro** [comment]
Se você olhar este campo pode ver que ele é um campo calculado, e ele representa apenas o que realmente falta pagar naquela parcela.
Se não me engano o value da ordem de cobrança utiliza ele.
Então value vai ser sempre igual ao amount_currency.

**Comment by Rynaro** [comment]
Então no caso, por convenção da refatoração da rotina, eu poderia delegar que o campo em questão deixe de receber esse campo de um objeto referenciado, e passar a consumir o value.
Estou fazendo o refactor pensando em manter a compatibilidade com o uso anterior do sistema, afim de evitar problemas de perda de referencia.

**Comment by danimaribeiro** [comment]
Alguma novidade quanto a este assunto?

**Comment by Rynaro** [comment]
No momento estou em processo de homologação da rotina junto ao Sicoob. Devo dizer que o suporte do mesmo tem um tempo bem "longo" para retornar sobre dúvidas, ou possíveis conflitos de sistema interno (o que eu já tive que enfrentar).

Sobre a feature, para evitar a quebra de informações de alguns campos que anteriormente eram dependentes de valores de objetos referenciados. Foi necessário criar campos computados _stored_, onde o mesmo consegue dar o handling do novo modo de uso, porém, não fazendo o projeto perder a referência anterior.
Assim evitando que o módulo perca compatibilidade com sistemas que já estão operando.
