### ISSUE TITLE
Ação Bloqueada ao validar boleto

### ISSUE THREAD

**Issue by Gersonsouzace** [Trust-Code/odoo-brasil#226]
Ação Bloqueada!
Para prosseguir é necessário preencher os seguintes campos:
Numeração da fatura deve ser menor que 12 caracteres quando usado boleto

**Comment by Rynaro** [comment]
Isso ocorre quando o **Código Abreviado** de seu diário de recebimento esteja superando o limite de 2 caracteres.
Experimente ir no diário referenciado e verificar a quantidade de caracteres que há nele. E experimente ajustar para o uso de 2 caracteres de tamanho, caso ele ultrapasse esse limite.

**Comment by Gersonsouzace** [comment]
Obrigado, problema resolvido.
