### ISSUE TITLE
Ocorreu um erro com a NFe numero xx

### ISSUE THREAD

**Issue by MatheusTanaques** [Trust-Code/odoo-brasil#227]
Sempre quando eu gero a danfe e retorno para a fatura o seguinte erro aparece:

Ocorreu um erro com a NFe de número 12. Visualizar NFe
-1 - [('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'wrong tag'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error')]
![sem titulo](https://user-images.githubusercontent.com/22055474/30595720-59bd3582-9d28-11e7-90fc-c07cf0a7fc40.png)

**Comment by danimaribeiro** [comment]
Verifique seu certificado digital.
