### ISSUE TITLE
Erro NF-e

### ISSUE THREAD

**Issue by Gersonsouzace** [Trust-Code/odoo-brasil#228]
Situação: -1
Mensagem: Opening and ending tag mismatch: HR line 1 and body, line 1, column 1110
Chave NFe:23170999086238000149550010000000211237343036
Protocolo Autorização:

`File "lxml.etree.pyx", line 3092, in lxml.etree.fromstring (src/lxml/lxml.etree.c:70473) File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106307) File "parser.pxi", line 1716, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105098) File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:99780) File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94254) File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:95690) File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:94757) XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and body, line 1, column 1110`

Outro erro que está acontecendo é : 

Ocorreu um erro com a NFe de número 20.170.044.
-1 - global name 'processa_rps' is not defined

**Comment by danimaribeiro** [comment]
Quais os passos para reprodução?
