### ISSUE TITLE
Erro quando tento VALIDAR: "Esse documento permite apenas serviços - Produto: 04588 - Quick 15 Min."

### ISSUE THREAD

**Issue by brennocg** [Trust-Code/odoo-brasil#234]
Poderiam me ajudar dizendo em que momento esse erro ocorre e o que estou deixando de configurar para gerar o erro?

ERRO: "Esse documento permite apenas serviços - Produto: 04588 - Quick 15 Min."

![erro_nfse](https://user-images.githubusercontent.com/20286547/30745270-d77a5c02-9f7b-11e7-9bd6-f5d4f7070f54.png)

**Comment by danimaribeiro** [comment]
O erro é auto-explanatório.

O documento configurado permite apenas serviços e não produtos.
