### ISSUE TITLE
Erro calculo de imposto 

### ISSUE THREAD

**Issue by reacps** [Trust-Code/odoo-brasil#24]
Olá pessoal!

Instalei o Odoo corretamente e sem erros com os addons para localização Brasil. Ativei os módulos de vendas , contábil e alguns Brasil. Configurei os impostos e, até mesmo utilizei os impostos já cadastrados, contudo, o cálculo não é feito! Sempre sai zerado! Criei outra base país canada e os impostos são calculados normalmente. Apenas a localização Brasil não está calculando nenhum imposto. Poderiam me ajudar?
Obrigado,
Renato

**Comment by danimaribeiro** [comment]
Como posso reproduzir o erro?

**Comment by reacps** [comment]
Olá Danimar,

Pode ser via teamviewer?

ID: 183 759 195
pass: 4751

Abraços,
Renato

**Comment by reacps** [comment]
Olá,

Parece que quando ativo o módulo de Plano de Contas Simplificado ou o Brazilian localisation zip code o erro acontece. Desativei o módulo e uso apenas o Vendas, Contabilidade e o imposto está funcionado da forma antiga (apertar o atualizar).

Abraços,
Renato

**Comment by rodriguesraphael** [comment]
O erro é não calcular os impostos?
Tem como printar a venda e a posição fiscal?

**Comment by reacps** [comment]
Olá,
Precisei desativar os módulos "Plano de contas simplificado" e "Brazilian Localisation ZiP codes". Estes dois módulos habilidade os impostos não funcionam em nenhum das telas (Cotação, Ordens e Fatura). Agora se deixarmos desabilitados e criando os impostos como retenção, a Cotação calcula corretamente, as ordens de venda também calculam corretamente, porém, a fatura não. Veja na imagem que ao invés da fatura seguir com a lógica da cotação / ordem ela está somando o impostos ao invés de subtrair.

<img width="2021" alt="screen shot 2016-12-22 at 9 24 58 am" src="https://cloud.githubusercontent.com/assets/16391951/21428616/e663c85a-c828-11e6-9801-b81786ecb56f.png">

<img width="1916" alt="screen shot 2016-12-22 at 9 25 14 am" src="https://cloud.githubusercontent.com/assets/16391951/21428666/3ef72520-c829-11e6-9da9-8fbb1cba6b12.png">

<img width="1869" alt="screen shot 2016-12-22 at 9 25 30 am" src="https://cloud.githubusercontent.com/assets/16391951/21428676/4908c2b2-c829-11e6-8708-c3d44ff20044.png">

Abraços,
Renato

**Comment by danimaribeiro** [comment]
Retenção ainda não funciona.
Devido a complexidade de impostos como ICMS, e ST os metodos de cálculo foram refeitos, e algumas configurações devem ser respeitadas no cadastro de imposto para que se funcione corretamente.

O "Tipo", "Calculo de imposto" e "Incluido no Preço" lá no cadastro de impostos são essenciais.

O Módulo "Plano de contas simplificado" já vem com algumas taxas configuradas corretamente, veja elas e quando for configurar seu imposto deve seguir o mesmo padrão.

**Comment by reacps** [comment]
Olá Danimar,
Desculpe se me expressei mal. Não quis dizer a funcionalidade de renteção do Oddo padrão. Na verdade, quis dizer impostos retidos na fonte. Os impostos estão configurados corretamente e utilizando o flag que voce mencionou. Inclusive, contabilizando correto quando não ativamos os dois módulos mencionados. Cotação e Ordens estão OK. O problema está sendo a fatura (ultima imagem da mensagem anterior). Ele considerar o imposto (que está incluído do preço onde na cotação e ordem saem negativos, corretamente), porém, na fatura sai positivo. Creio que a fatura deveria considerar o campo "valor liquido" para aí sim deixar o imposto somar.

Abraços 
Renato Campos

**Comment by reacps** [comment]
Adicionando mais duas imagens com os detalhes da fatura.

<img width="1864" alt="screen shot 2016-12-22 at 10 11 46 am" src="https://cloud.githubusercontent.com/assets/16391951/21429988/33021a1c-c82f-11e6-81b1-5d7386ba88cf.png">

<img width="1852" alt="screen shot 2016-12-22 at 10 14 00 am" src="https://cloud.githubusercontent.com/assets/16391951/21430053/7aeaef3e-c82f-11e6-9ba4-79fb473e8184.png">


Abraços
Renato Campos

**Comment by danimaribeiro** [comment]
Sem os passos corretos para reproduzir fica díficil descobrir o problema.
Mas posso te garantir que é apenas configuração. Quem cadastrou estes impostos?

Olha um exemplo de impostos na cotação e a mesma fatura gerada apartir da cotaçaõ.

![cotacao](https://cloud.githubusercontent.com/assets/854781/21430116/ea93623a-c848-11e6-9539-5c5b283e947d.png)
![exemplo de st](https://cloud.githubusercontent.com/assets/854781/21430126/ff156f0a-c848-11e6-8140-b17345f64f65.png)

**Comment by reacps** [comment]
Não testei impostos para venda mercantil. Estou tentando fechar um cenário de venda de serviços. Onde os impostos são retidos na fonte. Ou seja, o cliente recebe a fatura de 1755 e deve depositar 1647,06. A contabilização destes impostos devem cair em contas de retido da fonte e a conciliação bancária deverá ser do valor de 1647,06.

Vocês tem o cenário de venda de serviço?

Abraços
Renato Campos

**Comment by danimaribeiro** [comment]
Então, a retenção não funciona ainda.

**Comment by danimaribeiro** [comment]
Vou fechar o bug, pois não foi possível reproduzir. Funcionalidades faltantes não se classificam como bugs.
