### ISSUE TITLE
Fiz um clone do projeto, mudei os namespaces para flectra para poder ir avaliando.

### ISSUE THREAD

**Issue by eduardotd** [Trust-Code/odoo-brasil#252]
1 - Gostaria de saber se tem algum problema para a TrustCode.
2 - Vocês gostariam de alguma mudança no texto do README.md

Na realidade é exatamente o seu repositório apenas com a mudança dos namespaces.

Deixei o mais claro possível que a TrustCode não tem qualquer responsabilidade sobre o experimento que estou fazendo lá..

Grato desde já pela atenção...

**Comment by danimaribeiro** [comment]
Apenas mantenha os badges de licença, e seção sobre a licença do software.

**Comment by eduardotd** [comment]
Com certeza,  muito obrigado.
