### ISSUE TITLE
Erro com a dependência pytrustnfe

### ISSUE THREAD

**Issue by Aldo774** [Trust-Code/odoo-brasil#26]
![captura de tela de 2016-12-22 11-59-13](https://cloud.githubusercontent.com/assets/15001160/21427924/6f61386c-c83e-11e6-8367-0e1f40cb7ce7.png)

O seguinte erro ocorre quando realizo a atualização do módulo *br_base*. O pacote 'pytrustnfe' está instalado globalmente.
Entretanto, desaparece quando modifico a 'external_dependence' no *__manifest__.py* do *br_base* de 'pytrustnfe.nfe'  para 'pytrustnfe'

**Comment by danimaribeiro** [comment]
O seguinte comando executa sem erros?

python -c "import pytrustnfe.nfe"

**Comment by Aldo774** [comment]
Rodei o comando, retornou um erro reclamando da falta do *requests*, então o instalei, passou a reclamar a falta do *suds_requests*, logo após instalar o *suds_requests*, parei de ter problemas com a dependência *pytrustnfe*. 
Investiguei mais a fundo e tentei instalar o pytrustnfe através do **pip** dentro de uma *virtualenv*, ao rodar o **pip freeze** percebi que não constam *requests* e *suds_requests* em suas dependências. Ou seja, o pacote que está no *PyPi* esta desatualizado, sem a dependência *suds_requests*.

**Comment by danimaribeiro** [comment]
:+1: 

https://github.com/danimaribeiro/PyTrustNFe/pull/15
