### ISSUE TITLE
Erro na Impressão da DANFE

### ISSUE THREAD

**Issue by nogueira-raphael** [Trust-Code/odoo-brasil#290]
Traceback (most recent call last):
  File "/opt/odoo/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo/delta-addons/report_to_print/controllers/main.py", line 37, in index
    result.headers['Content-Disposition'] = result.headers['Content-Disposition'].replace('attachment', 'inline')
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 900, in __getitem__
    raise exceptions.BadRequestKeyError(key)
BadRequestKeyError: 400: Bad Request

**Comment by nogueira-raphael** [comment]
Sem o report_to_print retorna este erro:
cannot identify image file <cStringIO.StringO object at 0x7fb95efa56c0>
fileName=<cStringIO.StringO object at 0x7fb95efa56c0> identity=[ImageReader@0x7fb94d32f290]: (<type 'exceptions.IOError'>, IOError('cannot identify image file <cStringIO.StringO object at 0x7fb95efa56c0>\nfileName=<cStringIO.StringO object at 0x7fb95efa56c0> identity=[ImageReader@0x7fb94d32f290]',), <traceback object at 0x7fb94e0afef0>)

**Comment by crsilveira** [comment]
Tive o mesmo problema acima, 
e conforme dica do Raphael (acima), fiz a atualização do PILLOW e resolveu o problema.

**Comment by wspimentel** [comment]
No meu caso consegui solucionar o erro com esses passos. https://github.com/Trust-Code/odoo-brasil/issues/414
