### ISSUE TITLE
Danfe Odoo 11.

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#299]
Minha DANFE sai desconfigurada , como se não tivesse o css ou algo assim, no odoo 10 eu informava o "report.url"  e conseguia fazer, aqui não está indo, alguém já passou por isso ?

**Comment by crsilveira** [comment]
Refiz toda a configuraçaõ da DANFE, colocando o css necessário na mesma, se alguém precisar coloco aqui.

**Comment by danimaribeiro** [comment]
Na versão 11 e 10 foi removido o Danfe em html do Odoo.
Agora ele é gerado apenas pelo pytrustnfe.

**Comment by crsilveira** [comment]
Então, gerando ela em PDF , sai sem formatação, isso na 11, na 10 não tive problema.

**Comment by crsilveira** [comment]
Entendi o q vc disse agora, o que eu estou me referindo é o botão Imprimir DANFE, o que está no pytrustnfe, e o que vai por email .

**Comment by danimaribeiro** [comment]
Todos estão usando a mesma versão agora, do pytrustnfe.
Tenta atualizar seu código ai.

**Comment by crsilveira** [comment]
Está atualizado, não consigo achar o que é , segue onde passa:
br_nfe/models/account_invoice.py:
    def invoice_print(self):
        if self.product_document_id.code == '55':
            docs = self.env['invoice.eletronic'].search(
                [('invoice_id', '=', self.id)])
            **return self.env.ref(
                'br_nfe.report_br_nfe_danfe').report_action(docs)**
        else:
            return super(AccountInvoice, self).invoice_print(

Isto deveria chamar , a função abaixo ????

PyTrustNFe3-0.9.4-py3.5.egg/pytrustnfe/nfe/danfe.py

class danfe(object):^M                                                                                                                                                                                                                                                                                                                               
 -->>    def __init__

**Comment by danimaribeiro** [comment]
O mesmo já foi corrigido.
Está ok agora.
