### ISSUE TITLE
Erro para gerar o Cnab.

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#301]
/usr/local/lib/python3.5/dist-packages/python3_cnab-0.9.0-py3.5.egg/cnab240/registro.py

   Algum valor estava passando valor null pra esta função:
  adicionei o if abaixo nela.
    def removerAcentosECaracteresEspeciais(self, palavra):
        if not palavra:
            return False

**Comment by danimaribeiro** [comment]
Não achei essa função.
Porém o python3-cnab já está na versão 0.9.4
