### ISSUE TITLE
Toda vez que valido uma Fatura com NFe, o sistema busca nova numeração pra NFe.

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#308]
Caso o usuário valide e cancela a validação pra fazer algum ajuste que esqueceu, o sistema busca novo número pra NFe, interessa um PR, com ajustes pra que isso não aconteça ?

**Comment by danimaribeiro** [comment]
Então, como falei em outro issue. Já tentamos várias ideias, a que achamos melhor é não fazer nada mesmo, e deixar o usuário ajustar a numeração.
Em um ambiente com várias pessoas emitindo nota, fazer o ajuste automático da numeração teria efeitos colaterais.

Mas comenta a tua ideia aí, quem sabe pode resolver o problema.

**Comment by crsilveira** [comment]
Criei uma campo na Fatura  :  num_nfe : este campo carrega o número sequencial da nota, se o usuário precisar refazer alguma coisa,  e este campo estiver preenchido, o sistema mantém este número e não buscará a sequencia .

**Comment by danimaribeiro** [comment]
Se eu não emitir a nota no dia de hoje, e for emitir alguns dias depois e já foi emitido outros números sabe se dá algum problema de validação no sefaz?

**Comment by crsilveira** [comment]
Não sei te dizer se isto gera problema na troca de mês , dentro do mesmo mês sei que não tem problema.

**Comment by danimaribeiro** [comment]
Acho que pode ser feito dessa maneira sim:

> Criei uma campo na Fatura : num_nfe : este campo carrega o número sequencial da nota, se o usuário precisar refazer alguma coisa, e este campo estiver preenchido, o sistema mantém este número e não buscará a sequencia .

Como que eu poderia forçar para buscar um novo número?

**Comment by crsilveira** [comment]
Danimar eu fiz da forma abaixo, e os problemas com a numeração acabaram:

nfe_number_static = fields.Integer(
        string=u"Número NFe")

 def action_number(self, serie_id):
        if not serie_id:
            return
        nfe = self.env['invoice.eletronic']
        number_fim = nfe.search([
            ('serie', '=', serie_id.id),
            ('model', '=', '55'),
            ('emissao_doc', '=', '1')],   
            order='numero desc', limit=1).numero + 1  # emissao_doc uso no sped pra saber se é nf de emissao propria ou nao
        # verificando o ultimo numero nfe usado
        if self.nfe_number_static:
            # verifica se ja tem alguma nota com este numero
            number = nfe.search([('serie', '=', serie_id.id), ('numero','=',self.nfe_number_static)], order='numero desc', limit=1)
            if number:
                number_fim = number_fim
            else:    
                # mantenho o numero
                number_fim = self.nfe_number_static       
        return number_fim


 def _prepare_edoc_vals(self, inv, inv_lines, serie_id):
        res = super(AccountInvoice, self)._prepare_edoc_vals(
            inv, inv_lines, serie_id)
        numero_nfe = self.action_number(serie_id)
        res['payment_mode_id'] = inv.payment_mode_id.id
        if self.nfe_number_static != numero_nfe:
            self.nfe_number_static = numero_nfe
        ....
       
 Caso o usuário queira gerar um novo número , simplemente limpa o campo Número NFe (nfe_number_static)
