### ISSUE TITLE
Versão do Odoo e do Odoo-Brasil. 

### ISSUE THREAD

**Issue by gabrielcontessotto** [Trust-Code/odoo-brasil#311]
Boa tarde a todos. 

Estou com uma duvida estranha, sempre pensei que a versao do Odoo-Brasil deveria ser a mesma do Odoo.

Ou seja, se tenho o Odoo 10 tenho que usar a versão Odoo-Brasil 10. 

Só que tenho bastante certeza que cometi o seguinte erro, eu baixiei o Odoo-Brasil 11, sei disso pq usei o script de instalação de vocês e na linha onde baixa o odoo-Brasil está 

> git clone https://github.com/Trust-Code/odoo-brasil.git ~/odoo-brasil

Sei que linha logo acima que baixa o Odoo é a 

> git clone https://github.com/odoo/odoo.git ~/odoo

E teoricamente ambos serão 11, mas hoje estava verificando o sobre o Odoo e está escrito 10. 

Mas analisando o codigo do Odoo-Brasil vi que a versão dele é 11 meio bizarro será que vai dar problema?

**Comment by Rynaro** [comment]
A branch master dos repositórios da trustcode passaram de 10.0 para 11.0, faz algumas semanas.
Se você faz o clone sem especificar a branch, ele automaticamente vai buscar a branch master.
Para assegurar que você sempre vai ter a branch que precisa no seu environment, você precisa colocar a opção `-b 10.0`, por exemplo.
Vale ressaltar que a versão do Python usada na versão 10, para a 11 foi alterada. O que significa que pode ter efeitos colaterais sim.
