### ISSUE TITLE
Carga inicial de CFOPs

### ISSUE THREAD

**Issue by fnegrini** [Trust-Code/odoo-brasil#320]
Olá,

Possuo um certo background Fiscal e estou fazendo testes com o odoo-brasil. Percebi que não há lista de CFOPs pré-carregada e gostaria de contribuir com o repositório criando esta lista para carga através do módulo br_data_account.

**Comment by danimaribeiro** [comment]
O mesmo já existe:
https://github.com/Trust-Code/odoo-brasil/blob/11.0/br_data_account_product/data/br_account.cfop.csv

**Comment by fnegrini** [comment]
Na branch 10.0 não tem. Vou incluí-la e fazer um pull request. Pode ser?

**Comment by danimaribeiro** [comment]
Poder pode, mas tem na 10 também :)

https://github.com/Trust-Code/odoo-brasil/blob/10.0/br_data_account_product/data/br_account.cfop.csv

**Comment by fnegrini** [comment]
Vix! Devo ter pego a branch errada então.
Vou revisar hoje... Valeu!

**Comment by fnegrini** [comment]
Agora vi minha confusão. Estava esperando estes dados sendo carregados em br_data_account, pois é em br_account o model "br_account.cfop" é definido. Agora que vi que está em outro módulo.

Valeu!

**Comment by fnegrini** [comment]
Não faria mais sentido a carga estar em br_data_account?
