### ISSUE TITLE
Problema com diario no odoo

### ISSUE THREAD

**Issue by carlsec** [Trust-Code/odoo-brasil#345]
Galera quando vou validar a nota fiscal eletronica da o seguinte aviso

 Você não pode usar esta conta geral neste diário, verifique a aba 'Controles de Entrada' no diário relacionado. 

não estou encontrando essa eba, nem entendi o problema, alguem pra ajudar  ?

**Comment by danimaribeiro** [comment]
Habilitar modo desenvolvedor.

![controle](https://user-images.githubusercontent.com/854781/43982814-076a0dcc-9cce-11e8-96f8-d9182aad1327.png)
