### ISSUE TITLE
Descontos compondo base de cálculo do ICMS

### ISSUE THREAD

**Issue by nogueira-raphael** [Trust-Code/odoo-brasil#358]
Os descontos esstão compondo a base de cálculo do ICMS.
Mas descontos incodincionais não deveriam compor esta base de cálculo, apenas descontos condicionais.
Existe alguma configuração para que o desconto não seja incluído na Base de Cálculo do imposto?

**Comment by danimaribeiro** [comment]
Acho que é o contrário.
Não existe configuração para isso.

**Comment by nogueira-raphael** [comment]
Um exemplo:
Se eu vender um produto ao valor unitário de 1000 reais.
Dou um desconto de 10%.
Tenho um taxa de ICMS de 7%.
Neste caso o ICMS deveria ser calculado em cima do valor do produto 1000 reais.
Mas hoje no odoo o sistema calcula o ICMS em cima do valor com desconto já,
neste caso em cima de 900 reais, porém não deveria ser assim.

**Comment by danimaribeiro** [comment]
Não creio que seja dessa forma.
http://www.portaltributario.com.br/artigos/diferenca-entre-desconto-incondicional-e-desconto-condicional.htm

**Comment by Gesimieloliveira** [comment]
Até onde entendo o Danimar esta correto.

2018-03-07 15:04 GMT-03:00 Danimar Ribeiro <notifications@github.com>:

**Comment by Gesimieloliveira** [comment]
Sobre este tema, a Secretaria de Fazenda do Estado de São Paulo já se
manifestou através de Resposta à Consulta nº 5024/2015 e nº 2523/2013.

De acordo com a Resposta à Solução de Consulta da SEFAZ-SP, nas operações
com mercadorias cuja base de cálculo do imposto devido por substituição
tributária for o preço praticado pelo sujeito passivo acrescido do valor
resultante da aplicação de percentual de margem de valor agregado – IVA-ST
– (hipótese do artigo 41 “caput” do RICMS/2000), o valor referente ao
desconto incondicional concedido pelo substituto tributário não se incluirá
na formação da base de cálculo, pois o desconto incondicional não compõe o
preço da mercadoria (artigo 37, § 1º, item 1 do RICMS/2000 c/c § 4º e
inciso II, do artigo 8º da Lei Complementar 87/96).


2018-03-07 23:28 GMT-03:00 Gesimiel Oliveira <gesimiel.sistemas@gmail.com>:

**Comment by nogueira-raphael** [comment]
Vou verificar melhor peguei uma Nota Fiscal aqui e não estou entendendo.
Mas aproveitando o Issue, qual seria a forma correta de lançar uma desoneração de ICMS.
Informando um valor negativo no percentual, ex.: - 7%.
A nota fiscal veio com o valor do produto com icms incluso, mas no total a pagar tem o desconto do ICMS, como é isento.

**Comment by Gesimieloliveira** [comment]
*rodriguesraphael <https://github.com/rodriguesraphael> pra te dar uma
resposta clara sobre isso, vou precisar ver a nota, se possível me manda a
chave da nota fiscal.*

Em 8 de março de 2018 18:43, Raphael Rodrigues Nogueira <
notifications@github.com> escreveu:

**Comment by nogueira-raphael** [comment]
Olá @Gesimieloliveira , segu abaixo a Chave da Nota Fiscal conforme solicitado.
Chave NF-e: 42180209019836000102550010000205451773055272
Se verificar esta NF pode constatar as duas situações que mencionei, desoneração de ICMS neste exemplo o motivo é "7 - SUFRAMA" e também há o calculo do ICMS desconsiderando o desconto, no caso o ICMS ai foi calculado sem subtrair o desconto do valor do produto.

**Comment by danimaribeiro** [comment]
Isso ai está me parecendo que o pessoal está usando da artimanha para pagar menos imposto apenas.
Considerando que o valor da base do ICMS é o valor bruto para desonerar mais.

Como explicado no link descontos condicionais não podem ser descontados da base, pois estão são dados somente após a emissão da nota fiscal.
A base do ICMS geralmente representa o valor da operação, e não possível valor que seria pago.

**Comment by nogueira-raphael** [comment]
OK @danimaribeiro  sobre o desconto é um caso que também vi que na nota não me parece o correto a seguir, porém para o vendedor neste caso aí não foi vantagem alguma, o ICMS foi desonerado, quem pagaria o ICMS seria o comprador, neste caso ele teve que desonerar mais ainda o valor do produto(incluindo o desconto na BC do ICMS).
Mas a questão é, hoje a localização permite a desoneração de ICMS na posição fiscal, eu estou pensando em implementar esta opção, porém antes gostaria de saber se já não há esta opção.
