### ISSUE TITLE
SPED - ICMS/IPI

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#362]
Estou gerando o arquivo SPED acima pelo odoo 11, quero publicar o código , mas gostaria de falar com alguém da Trust-Code sobre alguns campos que precisei, pra publicar corretamente, meu skype é crsilveira.

**Comment by danimaribeiro** [comment]
Não pode ser comentado por aqui?
Ou são muitos campos e é complexo?

**Comment by crsilveira** [comment]
Para as notas de Entradas , precisaria destes campos (sei q já existem alguns, mas a série por exemplo, não dá pra usar a que tem): 
    nfe_num = fields.Integer('Num. NFe')
    nfe_serie = fields.Char('Série')
    nfe_modelo = fields.Char('Modelo')
    nfe_chave =  fields.Char('Chave NFe')
    nfe_emissao = fields.Date('Data Emissão NFe')

    num_item_xml = fields.Integer('N.Item')
    product_uom_xml = fields.Many2one('product.uom', string='Un.(xml)')
    product_qty_xml = fields.Float(string='Qtde(xml)', digits=dp.get_precision('Product Unit of Measure')) 
   
   class ProductTemplate(models.Model):
    _inherit = 'product.template'

    type_product = fields.Selection([
        ('00', u'Mercadoria Revenda'),
        ('01', u'Matéria Prima'),
        ('02', u'Embalagem'),
        ('03', u'Produto em Processo'),
        ('04', u'Produto Acabado'),
        ('05', u'Subproduto'),
        ('06', u'Produto Intermediário'),
        ('07', u'Material de Uso e Consumo'),
        ('08', u'Ativo Imobilizado'),
        ('09', u'Serviços'),
        ('10', u'Outros Insumos'),
        ('99', u'Outros')
     ], 'Tipo do Item',
    default='00'
# DESCRICAO DA UNIDADE DE MEDIDA
class ProductUom(models.Model):
    _inherit = 'product.uom'
    
    description = fields.Char('Descrição')

**Comment by danimaribeiro** [comment]
Aqueles campos já existem todos no documento eletrônico, a ideia do documento eletrônico era geralmente para esses casos do SPED, ter todos os campos que fossem necessário.
Será que não conseguimos uma maneira de mudar a interface para que a pessoa digite esses dados, mas gere um documento eletrônico vinculado ao invoice?

**Comment by crsilveira** [comment]
Então, no caso da NF de Entrada, não precisariamos ter este documento eletrônico .
Todas estas informações praticamente vem do xml da Nfe de Entrada .

**Comment by Mackilem** [comment]
Brother, eu sou o Mackilem da Trustcode... entra em contato comigo quero facilitar a tua vida. Me adiciona no skype é "mack.vdl" ou no hangout "mack.vdl@gmail.com"
