### ISSUE TITLE
[ br_account_payment ] not compatible with oca-bank-payment repo

### ISSUE THREAD

**Issue by yk2kus** [Trust-Code/odoo-brasil#365]
We got a conflict with oca-bank-payment repo. We have a field named "payment_mode_id" m2o with different objects in both repos. which isn't letting modules install and work together

// [trustcode-odoo-brasil/blob/10.0/br_account_payment/models/account_invoice.py](https://github.com/thinkopensolutions/trustcode-odoo-brasil/blob/10.0/br_account_payment/models/account_invoice.py)
`class AccountInvoice(models.Model):
    _inherit = 'account.invoice'

    payment_mode_id = fields.Many2one(
        'payment.mode', readonly=True,
        states=FIELD_STATE, string=u"Modo de pagamento")`

[OCA/bank-payment/blob/10.0/account_payment_partner/models/account_invoice.py](https://github.com/OCA/bank-payment/blob/10.0/account_payment_partner/models/account_invoice.py)

`class AccountInvoice(models.Model):
    _inherit = 'account.invoice'

    payment_mode_id = fields.Many2one(
        comodel_name='account.payment.mode', string="Payment Mode",
        ondelete='restrict',
        readonly=True, states={'draft': [('readonly', False)]})`

**Comment by danimaribeiro** [comment]
Won't be fixed.
