### ISSUE TITLE
NFSe SP

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#367]
A discriminação do serviço enviado está indo apenas uma linha no xml, esta truncando o texto, independente da forma que coloco :
 com \n ou  | ,  colocar "< br />"  não aceita...  alguma sugestão de como resolver ?

**Comment by crsilveira** [comment]
Segundo o manual da prefeitura (webservice), devia funcionar com o pipe "|" sem espaços , mas mesmo assim, vai tudo em uma linha, acredito q seja problema com o utf-8 ....

**Comment by crsilveira** [comment]
RESOLVIDO : 
o problema estava aqui no campo name , tamanho 100 :

class InvoiceEletronicItem(models.Model):
    _name = 'invoice.eletronic.item'

name = fields.Char(u'Nome', size=100, readonly=True, states=STATE)

**Comment by danimaribeiro** [comment]
Corrigido já.
