### ISSUE TITLE
Erro geração de NFS-e SP

### ISSUE THREAD

**Issue by guilhermetko** [Trust-Code/odoo-brasil#381]
Olá! 

(V10)

Estou fazendo uns testes com emissão de NFS-e com impostos retidos (Withholdings) , porém, ao emitir a nota esses impostos **não** estão sendo descriminados os seus valores: INSS, IRRF, CSLL, COFINS e PIS.
Além disso está sendo enviado como valor da nota o valor líquido, e não o bruto... 
Emissão feita pelo Odoo, valor da nota bruto é de 1000 e foi 938,50, além de não ter os impostos retidos:
![92d18649-59a7-432a-a6ce-6251bd74e710](https://user-images.githubusercontent.com/26436932/37692074-2c638cba-2c95-11e8-81d3-f2119018389b.jpg)

Temos um exemplo de nota com os campos de imposto supracitados preenchidos além de o valor total estar correto. Pode observar que o valor líquido está no corpo da nota - **esta não foi feita via Odoo.**
![screenshot_1](https://user-images.githubusercontent.com/26436932/37692219-0bd1f51c-2c96-11e8-9fdd-d5cbedcac8ef.png)

No nosso teste inserimos a posição fiscal que tinham os impostos Withholdings.

Seria possível nos suportar nesse tema? Precisamos emitir notas o quanto antes... Estou disponível para uma call se quiser.

Abs
Obrigado!

**Comment by danimaribeiro** [comment]
Fixed.
