### ISSUE TITLE
Erro 531 Rejeicao: Total da BC ICMS difere do somatorio dos itens. Como resolver??

### ISSUE THREAD

**Issue by gglimass** [Trust-Code/odoo-brasil#421]
Esse erro aparece após o envio da DANFE.
Tentei varias configurações de conf do icms e ate deixei zerado, mas o erro sempre aparece.

**Comment by gglimass** [comment]
O problema fora solucionado...
Cria-se a posição fiscal e a regra de ICMS sendo que a seleção do imposto deve ficar em branco.

**Comment by kcarriello** [comment]
na posição fiscal não devo colocar nada ou devo por ICMS com taxa 0%? E o cadastro do produto, você inclui algo no imposto pro cliente? O meu está dando este erro, já tentei várias soluções e nada. O erro só ocorre em vendas no POS.
