### ISSUE TITLE
Erro ao gerar CNAB 240 Itaú

### ISSUE THREAD

**Issue by brunobrobks** [Trust-Code/odoo-brasil#438]
Boa tarde,

Quando tento gerar o CNAB 240 ocorreo erro em anexo.

Odoo 11 Community - Ubuntu 17

![captura de tela de 2018-05-09 18-20-23](https://user-images.githubusercontent.com/31521178/39840415-b43898d2-53b5-11e8-9863-622b0d8efb6d.png)

Reparando o log do sistema encontro o seguinte erro em anexo:

![captura de tela de 2018-05-09 18-22-26](https://user-images.githubusercontent.com/31521178/39840488-f5d1c3a4-53b5-11e8-82d2-621e9b4790ce.png)

Desde já, agradeço a ajuda de todos!!!

**Comment by danimaribeiro** [comment]
Você precisa criar uma sequencia com o seguinte código:
seq.boleto.name
