### ISSUE TITLE
Error ao exportar NFE

### ISSUE THREAD

**Issue by alysonbg** [Trust-Code/odoo-brasil#444]
Bom dia,

Estou com um bug ao tentar utilizar o wizard de exportar as notas fiscais. Eu escolho uma data de início, data de fim e no documento nota fiscal eletrônica, porém, quando clico exportar, eu recebo a seguinte mensagem de error:

`  File "/home/vagrant/odoo-brasil/br_nfe/wizard/export_nfe.py", line 65, in nfse_export
    self.zip_file = self._save_zip(xmls)
  File "/home/vagrant/odoo-brasil/br_nfe/wizard/export_nfe.py", line 38, in _save_zip
    xml_file.write(xml['content'])
TypeError: write() argument must be str, not bytes`

No arquivo export_nfe.py, no método _save_zip, se eu alterar o modo de abertura do arquivo zip para 'wb' funciona normalmente.

`def _save_zip(self, xmls):
        tmp = '/tmp/odoo/nfse-export/'

        try:
            os.makedirs(tmp)
        except:
            pass
        zip_base64 = io.BytesIO()
        zip_file = ZipFile(zip_base64, 'w')
        for xml in xmls:
            filename = os.path.join(tmp, xml['name'])
            with open(filename, 'wb') as xml_file:
                xml_file.write(xml['content'])
            zip_file.write(filename, xml['name'])
        zip_file.close()
        zip_base64.seek(0)
        return base64.b64encode(zip_base64.getvalue())
`
Eu não tenho acesso a outra instalação do Odoo para ver se o erro é apenas aqui, teria como vocês tentarem reproduzir?

O modulo br_nfe está na versão mais atual.

Ps: O meu Odoo está na versão 11

**Comment by danimaribeiro** [comment]
Revolvido já.
