### ISSUE TITLE
NFe 4.0

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#448]
A Trust-Code está trabalhando na NFe 4.0, isto será liberado , se sim podemos ajudar ??

**Comment by danimaribeiro** [comment]
Ainda não, porém estou planejando um refactoring na lib pytrustnfe.
Se quiseres pode mandar PR neste branch
https://github.com/danimaribeiro/PyTrustNFe/tree/feature/nfe-4.0:
