### ISSUE TITLE
Total de Tributos : Imposto Federal Nacional e Importado , invertido ??!!!

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#476]
def _set_extimated_taxes(self, price):
        service = self.product_id.service_type_id
        ncm = self.product_id.fiscal_classification_id

        if self.product_type == 'service':
            self.tributos_estimados_federais = \
                price * (service.federal_nacional / 100)
            self.tributos_estimados_estaduais = \
                price * (service.estadual_imposto / 100)
            self.tributos_estimados_municipais = \
                price * (service.municipal_imposto / 100)
        else:
            **federal = ncm.federal_nacional if self.icms_origem in \
                ('1', '2', '3', '8') else ncm.federal_importado**
 
      esta ultima linha nao devia ser :     federal = ncm.federal_nacional if self.icms_origem == '0'   ??

**Comment by danimaribeiro** [comment]
Acho que seria:
('0', '3', '4', '5', '8')

**Comment by crsilveira** [comment]
sim, parece mais correto.
