### ISSUE TITLE
NFCe , odoo 10 - Rejeicao: Assinatura difere do calculado

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#477]
Estou usando o odoo 10 e PyTrustNFe (última versão , com ajustes para rodar no python 2.7), consegui gerar o XML, passa na validação, mas dá erro: 

   Rejeicao: Assinatura difere do calculado

Validei tbém por aqui : https://www.sefaz.rs.gov.br/nfe/NFE-VAL.aspx , 
mesma mensagem, alguma dica de como conseguir localizar o erro ?

**Comment by danimaribeiro** [comment]
Tenta novamente, talvez agora esteja certo a NFCe.
