### ISSUE TITLE
Problemas NF-e

### ISSUE THREAD

**Issue by thiago95macedo** [Trust-Code/odoo-brasil#5]
Por favor corrija os erros antes de prosseguir
Configure a posição fiscal
CFOP
____________________________________________________________________
O campo de configurar a posição fiscal não tem nenhuma opção para selecionar.
Já o CFOP não achei o campo para ser configurado.

Alguma ajuda?

**Comment by danimaribeiro** [comment]
É necessário criar uma posição fiscal.

o CFOP está na linha do item:
![cfop](https://cloud.githubusercontent.com/assets/854781/20639960/9533ede4-b3b9-11e6-829a-3d0069238d50.png)
