### ISSUE TITLE
Odoo v10 com PyTrustNFE

### ISSUE THREAD

**Issue by felipeelopes** [Trust-Code/odoo-brasil#503]
Boa Tarde,
a versão 10 do ODOO é compatível com a última versão disponível no repositório do PyTrustNFE? Ou somente com a versão disponibilizada no pip?

**Comment by felipeelopes** [comment]
Tentei rodar o Odoo 10 com a última versão porém como o PyTrustNFE é em Python 3 e o Odoo 10 em Python 2.7 tive problemas.

**Comment by crsilveira** [comment]
Felipe , tenho aqui , veja se te ajuda : https://github.com/crsilveira/PyTrustNFe/tree/nfe-4.0_odoo10

**Comment by felipeelopes** [comment]
Ajuda muito, vou ajudar a manter a repo atualizada. Obrigado!

**Comment by danimaribeiro** [comment]
10.0 - pytrusnfe
11.0 - pytrustnfe3
