### ISSUE TITLE
Server Error 500 webservice envio NFe MT 

### ISSUE THREAD

**Issue by deyvsonaguiar** [Trust-Code/odoo-brasil#513]
Ao enviar a NFe no meu ambiente 10.0 com a última atualização de vocês (10.0) eu realizei o envio no ambiente de homologação mas deu o seguinte erro: 

Situação: -1
Mensagem: 500 Server Error: Internal Server Error for url: https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao
Chave NFe:51180824655484000175550010000001081423205476
Protocolo Autorização:

Ao consultar a Sefaz-MT vi que não existe mais esse Webservice, podem me dizer como resolver? Segue consulta dos webservices para o MT: 

https://homologacao.sefaz.mt.gov.br/nfews/v2/services/NfeAutorizacao

Creio que se a nova atualização ainda conter endereços antigos ou desatualizados, poderá fazer um novo merge da 10.0 com os novos endereços para homologação e produção para nosso Estado. Tem sido muito útil o odoo por aqui.

Desde já obrigado.

**Comment by danimaribeiro** [comment]
Atualizar a lib pytrustnfe resolve o problema.
