### ISSUE TITLE
[BR_localization_filtering] Remove inherit field 'note' in account_fiscal_position module

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#521]
Hi @danimaribeiro 
I've noticed that account_fiscal_position module in brazilian localization has inherit the field "note", I think the porpouse of this inherit is only for changing field texts. is it right?

https://github.com/Trust-Code/odoo-brasil/blob/70a1b5bb3206f82f36ae647fbb9bec01a0f71fe6/br_account/models/account_fiscal_position.py#L87

We can change the string and help text with translations files. Can we remove this field? 

Thanks!

**Comment by danimaribeiro** [comment]
Yes, free to remove if it exists

**Comment by ghost** [comment]
👍 

Thanks!
