### ISSUE TITLE
Error inheriting city_id field in res_partner module

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#525]
Hi @danimaribeiro ,

As we agree in the meeting, we have a problem with city_id field in multilocalization environment. This field is inheriting from res_partner module overriding the model relation (res.city -> res.state.city).

https://github.com/Trust-Code/odoo-brasil/blob/86719271cdfeb5d38c0b9ec8c34fe718bd14eddb/br_base/models/res_partner.py#L37-L39

Odoo has a module called base_adress_city with the same inheritance but use res.city model for this relation.

https://github.com/odoo/odoo/blob/21064c7de8867c9217d274cb83ff589c8ebcac75/addons/base_address_city/models/res_partner.py#L14

Brasilian localization overrides the method _onchange_city_id() without super.

https://github.com/Trust-Code/odoo-brasil/blob/86719271cdfeb5d38c0b9ec8c34fe718bd14eddb/br_base/models/res_partner.py#L157-L165

https://github.com/odoo/odoo/blob/ebf29dfc2e76506e021042008fa7a8e061388658/addons/base_address_city/models/res_partner.py#L16-L20

If other module is overriding this method can change the behaviour making an error arise because res.state.city model hasn't got same fields than res.city.

My proposal for fix this issue:
1.- Modify res_state_city model in br_base to res.city inheriting new fields (ibge_code)

```
class ResCity(models.Model):
    """ Este objeto persite todos os municípios relacionado a um estado.
    No Brasil é necessário em alguns documentos fiscais informar o código
    do IBGE dos município envolvidos da transação.
    """
   _name = 'res.city'
   _description = u'City'

    ibge_code = fields.Char(string=u'IBGE Code', size=7, copy=False)
```

2.- Modify relation model in all the modules has city_id field.

```
class ResRegion(models.Model):
    _name = 'res.region'

    name = fields.Char(string="Name", size=100)
    city_ids = fields.Many2many('res.city', string="Cities")
    state_ids = fields.Many2many('res.country.state', string="States")
```

Other proposal is prefixing city_id field with l10n_br but I think the first proposal is better.

What do you think @danimaribeiro? I can add this change according your feedback while I'm filtering brasilian fields.

**Comment by danimaribeiro** [comment]
I was not aware of that module.

Yep, let's use the core module from odoo but I want this change to be in another branch.
I have to think a way to migrate all the databases.

**Comment by ghost** [comment]
Thanks @danimaribeiro ,  If you need some help don't heasitate to tell me.

**Comment by ghost** [comment]
Hi @danimaribeiro ,

As we talked in last meeting, this issue is blocking for us. When you can solve this issue? 

Thanks!

**Comment by danimaribeiro** [comment]
I tried to have one time migration, but I don't think is possible.

I'll try this one:
https://github.com/Trust-Code/odoo-brasil/pull/619

- [X] Create a copy of table res_state_city to res_city and update the databases.
- [ ] Add base_address_city to dependencies and install and update br_base.

**Comment by ghost** [comment]
@danimaribeiro , maybe you can add to depends the module base_address_city. 

![image](https://user-images.githubusercontent.com/12764560/47031658-991a9a80-d170-11e8-89cd-45816a0decea.png)

It has the model res.city and it creates the table res_city. Once created you can set res_state_city on res_city.

I hope this help you.

**Comment by danimaribeiro** [comment]
I tried that, but it does not work, because this module tries to change the foreign key of city_id for the new table and it fails to install.

I had a new idea of disabling foreign keys temporarily, but I don't know how to execute this before the module instalation without changing the code directly.

**Comment by ghost** [comment]
I've not tried but you can modify pre-migration.py with the following steps:
1.- Create dummy_partner_city_table with city_id of the partners
2.- Set city_id = null in res_partners table

Then, once the new module has been installed, with post-migration.py update res_partner table with the city_id.
