### ISSUE TITLE
Erro data da Nota Fiscal

### ISSUE THREAD

**Issue by zztecnet** [Trust-Code/odoo-brasil#537]
Boa noite a todos, estou testando a versão 11 do Odoo, e ao enviar uma nota fiscal utilizando o mpodulo desenvolvido pela Trustcode recebo o erro:
Situação: 703
Mensagem: Rejeição: Data-Hora de Emissão posterior ao horário de recebimento

Ao conferir o XML, vejo que a data está a padrão da base do sistema que acho que fuso horário de Londres.
Alguém sabe qual arquivo que define esse horário para nota fiscal?

**Comment by luiz-alonso-zz** [comment]
Estou com um problema parecido, só que ao invés de horário superior o meu está inferior, um pouco ante de começar aparecer este erros , o emissor estava funcionado perfeitamente em modo homologação, quando voltei para fazer só mais alguns teste antes de passar para produção começou aparecer este erro 

Situação: 900
Mensagem: Rejeição: Data de vencimento da parcela não informada ou menor que Data de Emissão [nOcor: 2]

olhei o xml e pelo que pesquisei sobre o erro meu xml está normal tudo em ordem.

**Comment by luiz-alonso-zz** [comment]
zztecnet 

Consegui resolver o erro da seguinte forma

OBS: não sei se é a melhor forma más se quiser fique a vontade

vá ao seu terminal e de um stop no odoo

baixe a versão mais atual do repositório do odoo brasil

extraia copie e cole a pasta br_nfe por cima da outra pasta que está na pasta addons

faça um backup da br_nfe orginal antes de mesclar os arquivos

depois e só iniciar o processo novamente e tentar enviar caso de algum problema desfaça essa alteração utilizando o backup e aguarde a resposta oficial do desenvolvedor.

**Comment by zztecnet** [comment]
Obrigado. Consegui resolver. Um outro problema que enfrento agora e quando, um produto termina com R$10,00, que o sistema arredonda para 10,01 o que dá inconsistência no valor líquido.
Parece um problema de arrendidamento de valores. Alguém passou por esse problema?

**Comment by luiz-alonso-zz** [comment]
Olá zztecnet tudo bleleza

Eu já tive um problema parecido, não sei se a causa e a mesma, más resolvi da seguinte forma.

Vá em Faturamento -> Configurações ->  e verá uma opção nomeado como Método de arredondamento
o me estava selecionado " Arredondamento Global " e mudei para " Rodada por linha " e nunca mais tive este problema, Boa Sorte !

**Comment by zztecnet** [comment]
Obrigado amigo. O erro continua. Acredito que tenha relação com o cálculo do PIS, que quando o valor termina com R$10,00 arredonda para R$0,07, mas 1 centavo acaba sendo somado ao valor total da cobrança.
