### ISSUE TITLE
PDV Produto Personalizavel

### ISSUE THREAD

**Issue by megaterrarc** [Trust-Code/odoo-brasil#539]
Bom dia

    Estou realizando a implantação do odoo em um cliente de pastelaria que vende pasteis personalizáveis. Gostaria de saber se aqui possui uma extensão para essa funcionalidade.

Ex. Produto Pastel Medio 2 sabores. Na seleção no PDV teria que escolher 2 sabores, como em uma pizzaria

**Comment by danimaribeiro** [comment]
Não, aqui só existem módulos relacionados a adaptar o Odoo a legislação brasileira.
