### ISSUE TITLE
Duplicate field

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#545]
Hi @danimaribeiro,

I don't know if for some reason this field is duplicate in account_invoice_line module:

https://github.com/Trust-Code/odoo-brasil/blob/409c924854ddd236ec6aaa2ab33a29d69dd1176f/br_account_einvoice/models/account_invoice.py#L277-L287

https://github.com/Trust-Code/odoo-brasil/blob/409c924854ddd236ec6aaa2ab33a29d69dd1176f/br_nfse/models/account_invoice.py#L44-L54

Can we remove it from br_nfse module?

Thanks!

**Comment by danimaribeiro** [comment]
Yes, it can.

**Comment by ghost** [comment]
Thanks!
