### ISSUE TITLE
Rejection: No editing characters are allowed at the beginning / end of the message or between the message tags

### ISSUE THREAD

**Issue by pank37** [Trust-Code/odoo-brasil#558]
please help me to remove some unexpected text in file
![aaaaa](https://user-images.githubusercontent.com/41303099/44851803-19e40c80-ac7f-11e8-91f6-2f8923103fb9.jpg)

**Comment by danimaribeiro** [comment]
How to reproduce?

**Comment by pank37** [comment]
when things setup everything was working perfect, suddenly some of invoice raise this error. May be xml file contains some byte code or some other invalid char.
Is reproduce good solution? what if it happen again?
Is there any way to handle it before send?

**Comment by pank37** [comment]
Hi @danimaribeiro

Please check screenshot, I tried  to fix this issue. I remove space and tab just before send.
Every time this issue raise with item number 35
when I try to remove space and tab new issue raise "Rejeição: Assinatura difere do calculado"
Please help me

![screen shot 2018-09-30 at 10 57 47 am](https://user-images.githubusercontent.com/41303099/46253690-f986b800-c49f-11e8-99e9-de5592519fa7.png)

**Comment by danimaribeiro** [comment]
I solved this issue last week:
https://github.com/danimaribeiro/PyTrustNFe/commit/21994c73e8be6cdd69991892cddd68a0f517748b
