### ISSUE TITLE
Tabela IBPT não importa na versão 11

### ISSUE THREAD

**Issue by Daniel-Furcht** [Trust-Code/odoo-brasil#579]
Na versão 11, ao usar o Wizard de importação da tabela IBPT, o procedimento termina sem erros, mas os campos de impostos permanecem zerados.
Na versão 10 este procedimento funciona normalmente.

**Comment by danimaribeiro** [comment]
Tem alguma planilha para testar?

**Comment by Daniel-Furcht** [comment]
Segue a tabela que testei na versão 10. A propósito o encode não é UTF-8...
[TabelaIBPTaxRS18.2.C.zip](https://github.com/Trust-Code/odoo-brasil/files/2421628/TabelaIBPTaxRS18.2.C.zip)

**Comment by danimaribeiro** [comment]
#583
