### ISSUE TITLE
Erro na geração de NFE (XML) para produtos com código de barras cadastrado (cEAN e cEANtrib)

### ISSUE THREAD

**Issue by carlos-korovsky** [Trust-Code/odoo-brasil#60]
Quando o produto possuí o código de barras cadastrado (EAN) o XML é gerado incorretamente:
```
<prod>
  <cProd>TL-WA901ND</cProd>
  <cEAN/>
  <cEAN>6935364051426</cEAN>
  <xProd>NOTA FISCAL EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>
  <NCM>85176277</NCM>
  <CFOP>5102</CFOP>
  <uCom>UN</uCom>
  <qCom>1.0</qCom>
  <vUnCom>279.00</vUnCom>
  <vProd>279.00</vProd>
  <cEANTrib/>
  <cEANTrib>6935364051426</cEANTrib>
  <uTrib>UN</uTrib>
  <qTrib>1.0</qTrib>
  <vUnTrib>279.00</vUnTrib>
  <indTot>1</indTot>
</prod>
```
Note a repetição das TAGs cEAN e cEANTrib (uma vazia e outra preenchida). Retirando o código EAN do cadastro do produto a emissão ocorre sem problemas. A tag xProd está sendo preenchida corretamente?

PyTrustNFe (0.1.18)  - PyTrustNFe é uma biblioteca para envio de NF-e
  INSTALLED: 0.1.18 (latest)

Repositórios odoo.git e odoo-brasil.git atualizados em 06/01/2017 às 13:00

**Comment by danimaribeiro** [comment]
Fixed https://github.com/danimaribeiro/PyTrustNFe/pull/20
