### ISSUE TITLE
psycopg2.ProgrammingError: column res_company.l10n_br_nfse_conjugada does not exist

### ISSUE THREAD

**Issue by aledr** [Trust-Code/odoo-brasil#605]
Após atualizar para o commit 50409dee822f568f20870702b28e3099b1fe93e8 do branch 11.0 de 02/outubro o erro abaixo é apresentado.

psycopg2.ProgrammingError: column res_company.l10n_br_nfse_conjugada does not exist

**Comment by danimaribeiro** [comment]
Atualize sua base.
