### ISSUE TITLE
Erro ao inserir certificado digital em empresa. V12

### ISSUE THREAD

**Issue by marcelsavegnago** [Trust-Code/odoo-brasil#608]
Estou rodando a versão 12 do Odoo com a localização Brasil em um Ubuntu 18.04. Ao fazer o upload do certificado digital , digitar a senha e salvar é informado um Status desconhecimento. Segue abaixo. trecho do log. 

_Observação, para concluir a instalação no Ubuntu 18 precisei alterar o arquivo requirements.txt para instalar a ultima versão do pillow.. não sei se isto poderia influenciar._

> 2018-10-10 18:36:43,485 871 WARNING fmi-prod odoo.addons.br_base.models.res_company: Erro desconhecido ao consultar o certificado 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/odoo/api.py", line 1032, in get
>     value = self._data[field][record.id][key]
> KeyError: <odoo.api.Environment object at 0x7f64c8489898>
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/odoo/fields.py", line 970, in __get__
>     value = record.env.cache.get(record, self)
>   File "/opt/odoo/odoo/odoo/api.py", line 1034, in get
>     raise CacheMiss(record, field)
> odoo.exceptions.CacheMiss: ('res.company(1,).cert_state', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/addons/odoo-brasil/br_base/models/res_company.py", line 93, in _compute_expiry_date
>     self.cert_expire_date = end
>   File "/opt/odoo/odoo/odoo/fields.py", line 992, in __set__
>     value = self.convert_to_cache(value, record)
>   File "/opt/odoo/odoo/odoo/fields.py", line 1605, in convert_to_cache
>     raise TypeError("%s (field %s) must be string or date, not datetime." % (value, self))
> TypeError: 2019-05-08 20:02:33 (field res.company.cert_expire_date) must be string or date, not datetime.

**Comment by camilorodegheri** [comment]
+1

**Comment by camilorodegheri** [comment]
A correção é simples. Mudou de datetime para date.
self.cert_expire_date = end.date()

**Comment by danimaribeiro** [comment]
Já corrigido.
