### ISSUE TITLE
Erros identificados ao incluir sub módulo no Odoo.sh - V12

### ISSUE THREAD

**Issue by marcelsavegnago** [Trust-Code/odoo-brasil#615]
Boa tarde. Estou testando a V12 no Odoo.sh e ao incluir a localização como submódulo o Odoo.sh emite alguns alertas conforme imagens abaixo:

![image](https://user-images.githubusercontent.com/3595132/46964135-cf2b2200-d07d-11e8-8405-ee1e04a07f99.png)
![image](https://user-images.githubusercontent.com/3595132/46964177-eb2ec380-d07d-11e8-9813-20d2e6d73337.png)
![image](https://user-images.githubusercontent.com/3595132/46964301-1fa27f80-d07e-11e8-98c0-f9825a94128b.png)

**Comment by danimaribeiro** [comment]
odoo.sh não é suportado ainda.
Contribuições para corrigir os problemas serão aceitas.

**Comment by marcelsavegnago** [comment]
> odoo.sh não é suportado ainda.
> Contribuições para corrigir os problemas serão aceitas.

Grande Danimar. Obrigado pelo retorno e farei o possível para contribuir.
