### ISSUE TITLE
Módulos BR Faltando instalador

### ISSUE THREAD

**Issue by TecSecret** [Trust-Code/odoo-brasil#64]
Os módulos Point Of Sale Brasil (NFCe), Método de entrega no Brasil, Website Sale Checkout Fields for Brazil está faltando instalador ou o mesmo não é reconhecido.

Atualizado do git é a última disponível até está data.
![erro odoo](https://cloud.githubusercontent.com/assets/6561517/21738246/dc30cd58-d460-11e6-9e53-514e49c08e72.jpg)

Alguém sabe o porque disto, já troquei até de banco de dados, acredito que possa ser algum pré-requisito, ma no repo não achei nada.

Uso ubuntu 16.10.

**Comment by danimaribeiro** [comment]
Fixed https://github.com/Trust-Code/odoo-brasil/pull/65
NFCe e delivery não estão prontos.
