### ISSUE TITLE
[11.1]Field l10n_br_payment_mode_id thats exists in other module has attribute oldname 

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#647]
Hi @danimaribeiro ,

We have a problem with attribute oldname of field payment_mode_ir in account_invoice and account_move_line model.
We have these modules installed: https://github.com/OCA/bank-payment/tree/11.0/account_payment_partner, https://github.com/OCA/bank-payment/tree/11.0/account_payment_order that already contains this field so Odoo is crashing when I install Brazilian localization because these fields are related account.payment.mode model instead of payment.mode.

I think the best solution for solve this problem is:
1.- Remove oldname attribute to fields that are currently prefixed 
2.- Add prefix to payment_mode_id fields in the rest of the modules
3.- Install Brazilian localization with new field (l10n_br_payment_mode_id)
4.- Copy the value of payment_mode_id to l10n_br_payment_mode_id in case of company has Brazilian Chart

What do yo think? Do you need to develop step 4 or can we assume that version 11.1 will install database from the scratch?

Thanks!

**Comment by danimaribeiro** [comment]
You can remove the attribute and add prefix.

I'll prepare migration scripts to branch 11.1 latter.

**Comment by ghost** [comment]
Ok! Thanks!

**Comment by ghost** [comment]
@danimaribeiro, I think we can close this issue.
