### ISSUE TITLE
Erro na atualização do br_boleto

### ISSUE THREAD

**Issue by crsilveira** [Trust-Code/odoo-brasil#662]
File "/opt/odoo/odoo/odoo/fields.py", line 508, in _setup_related_full
    field = target._fields[name]
KeyError: 'boleto'

o erro ocorre na linha abaixo:

class AccountInvoice(models.Model):
    _inherit = 'account.invoice'

    # AQUI :
    boleto = fields.Boolean(related="payment_mode_id.boleto")

**Comment by danimaribeiro** [comment]
Não ocorre esse erro aqui, acho que só precisa atualizar.
