### ISSUE TITLE
[11.0] Campo custo para nfe ou invoice

### ISSUE THREAD

**Issue by maiconkkl** [Trust-Code/odoo-brasil#679]
Estava percebendo que não existe um campo de custo para as NF-e e isso impossibilidade criada de um relatório como por exemplo lucro bruto ou até mesmo para histórico da venda.
Gostaria de saber se estou incorreto ou posso fazer a criação do mesmo e enviar um PR.

**Comment by danimaribeiro** [comment]
Já existe custo no produto:
https://github.com/odoo/odoo/blob/12.0/addons/product/models/product.py#L567

**Comment by maiconkkl** [comment]
Uma outra duvida... Existe alguma forma disso retornar um ID ?
No caso do exemplo acima, preciso montar um relatório de lucro bruto por NF-e, eu tenho uma lista de custos em uma certa data.
Como vou relacionar o custo a NF-e ou invoice claro...

Caso não exista essa relação, existe alguma função parecida com **def _set_standard_price(self, value):**
que retorne o ID para ser criado alguma relação ?

**Comment by danimaribeiro** [comment]
Nota fiscal -> Linhas da Nota -> Produto -> Custo do produto em certa data.

Acho que você consegue montar uma consulta em cima disto.

**Comment by maiconkkl** [comment]
Vlw pela força, vou dar uma analisada, dar uma olhada no meu pull request, ja corrigir os erros e melhorei um pouco.
