### ISSUE TITLE
Erro na geração do arquivo XML, para NFE com vários produtos.

### ISSUE THREAD

**Issue by carlos-korovsky** [Trust-Code/odoo-brasil#69]
Quando tenta-se emitir uma nota fiscal com vários produtos cadastrados, retorna o seguinte erro da receita federal: `225 - Rejeicao: Falha no Schema XML do lote de NFe`.
Acredito que este seja o motivo, o valor nItem não está sendo incrementado:
```
<det nItem="1">
  <prod>
     <cProd>TL-WA901ND</cProd>
     <cEAN>6935364051426</cEAN>
     <xProd>Access Point TP-Link TL-WA901ND 300Mbps</xProd>
...
</det>
<det nItem="1">
   <prod>
      <cProd>TL-WA901ND-V2</cProd>
      <cEAN/>
      <xProd>Access Point TP-Link TL-WA901ND 450Mbps</xProd>
...
</det>
```
A nota foi emitida para o estado de Santa Catarina, venda dentro do estado.
Versões:
   - Odoo e brasil-odoo atualizados em: 2017-01-09
   - PyTrustNfe: 0.1.19

**Comment by danimaribeiro** [comment]
https://github.com/pallets/jinja/issues/641
Sugiro fixar a versão do Jinja2 por enquanto.

Jinja2>=2.8,<2.9

**Comment by danimaribeiro** [comment]
A principio corrigido aqui:
https://github.com/danimaribeiro/PyTrustNFe/pull/22

**Comment by zimbora69** [comment]
Hello,

I runned the setup.py from https://github.com/danimaribeiro/PyTrustNFe and Still have this issue on my localhost.

**Any clues how I might fix this issue?**
