### ISSUE TITLE
Erro no calculo de tributação do ICMS

### ISSUE THREAD

**Issue by ImplantiSolucoes** [Trust-Code/odoo-brasil#716]
Bom dia, estava fazendo alguns testes na parte de calculo de imposto e percebi a seguinte situação, eu coloquei um produto no valor $ 3.044,15 e com tributação de ICMS a 12% e ele gerou esse erro. O calculo deveria dar 365,30, mas gerou o valor de 326,16

Veja o print do erro
![image](https://user-images.githubusercontent.com/39229285/49939604-7385e500-fec4-11e8-9d51-82cb30e52fe3.png)

Configuração do imposto:
![image](https://user-images.githubusercontent.com/39229285/49939849-18082700-fec5-11e8-9319-63db19717ae2.png)
![image](https://user-images.githubusercontent.com/39229285/49939870-28b89d00-fec5-11e8-96c9-112b54c700bc.png)

Versão 11

**Comment by ImplantiSolucoes** [comment]
Dando uma lida no codigo, percebi que o calculo correto esta na opção Imposto de Percentagem de Preço Incluído e não em Percentagem do Preço, mas a pergunta é... Qual imposto de encaixa na segunda opção ?

**Comment by ImplantiSolucoes** [comment]
Eu percebi que o sistema alguma não faz o calculo de ajuste de retirada do valor do ICMS da base de calculo do pis e confins e como a noticia que houve recentemente da retirada do pis e confis da base de calculo, o ideal é reajustar o calculo, mas não estou encontrando a parte que consiga fazer essa alteração...
https://www.conjur.com.br/2018-dez-11/justica-cassa-restricao-exclusao-icms-pis-cofins?utm_source=dlvr.it&utm_medium=facebook

**Comment by danimaribeiro** [comment]
Apenas a configuração do imposto que está incorreta.
Percentagem do preço, ex: IPI
