### ISSUE TITLE
[11.1] The operation cannot be completed due to deletion, creation/update

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#718]
Hi @danimaribeiro ,

I'm finding a problem with 11.1 branch and multilocalization database when I'm creating a invoice from purchase order.

![image](https://user-images.githubusercontent.com/12764560/50012016-d7d89f80-ffbd-11e8-9deb-ef1514187030.png)

![image](https://user-images.githubusercontent.com/12764560/50012069-f8085e80-ffbd-11e8-8a68-4a0173fc6dd8.png)

The problem is the default attribute in l10n_br_product_type field ->

https://github.com/Trust-Code/odoo-brasil/blob/11.1/br_account/models/account_invoice_line.py#L241-L244

The same case happens with some base fields (l10n_br_icms_tipo_base, 'l10n_br_icms_st_tipo_base'), if localization is different to Brazilian, the method _prepare_invoice_line_from_po_line nos set value in this fields. 

This fields has default attribute, ¿Can I delete required attribute from .py?

Thanks!

**Comment by danimaribeiro** [comment]
Yes you can remove.

**Comment by ghost** [comment]
Thanks @danimaribeiro !
