### ISSUE TITLE
Emitente

### ISSUE THREAD

**Issue by ImplantiSolucoes** [Trust-Code/odoo-brasil#746]
Quando configuro o emitente com o número 38 ou destinatário gera esse problema, porém quando eu coloco 038 passa normal:
Element '{http://www.portalfiscal.inf.br/nfe}nro': [facet 'pattern'] The value '38' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.
Element '{http://www.portalfiscal.inf.br/nfe}nro': '38' is not a valid value of the local atomic type.

**Comment by danimaribeiro** [comment]
Atualizar o lxml.
