### ISSUE TITLE
erro xml ambiente de homologação

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#76]
ao enviar nfe aparece o seguinte status

Situação: 225
Mensagem: Rejeicao: Falha no Schema XML do lote de NFe

**Comment by danimaribeiro** [comment]
Usa esse link aqui para ver o problema
https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx

**Comment by ewertonmagalhaes** [comment]
ok, alguns caracteres especiais não são aceitos no campo de endereço

**Comment by danimaribeiro** [comment]
Consegue me dizer quais caracteres?

**Comment by danimaribeiro** [comment]
Fix - https://github.com/danimaribeiro/PyTrustNFe/pull/26
