### ISSUE TITLE
Módulo br_nfse_ginfes >= 11.0

### ISSUE THREAD

**Issue by marcelsavegnago** [Trust-Code/odoo-brasil#762]
Estou gerando a nota fiscal de serviço e está dando o seguinte erro quando clico em ENVIAR:

'str' object has no attribute 'decode'

Pesquisando percebi que este problema ocorre com o python3 e uma sugestão de solução que encontrei foi modificar o código adicionando encode('utf-8') mas não fiz nenhum teste;

->  recebe_lote['received_xml'].encode('utf-8').decode('utf-8'))

https://github.com/Trust-Code/odoo-brasil/blob/80ef42ce3760dc3ea739500703425c509fdd07f9/br_nfse_ginfes/models/invoice_eletronic.py#L274

**Comment by danimaribeiro** [comment]
Fixed.
