### ISSUE TITLE
br_boleto - Espécie de Titulo - V 11.0

### ISSUE THREAD

**Issue by marcelsavegnago** [Trust-Code/odoo-brasil#763]
Estou utilizando o Odoo 11.0 e a Localização Trust-Code 11.0.

Configurei o boleto do banco do brasil com a especie de titulo Duplicata Mercantil. Desta forma consegui gerar os boletos corretamente. Porém, ao gerar o arquivo CNAB a especie do tiulo registrado no banco é Cheque. 

Ao verificar o arquivo de remessa percebi que o código de especie de titulo está como o valor 01 (pos. 107 a 108) e o correto seria 02 segundo o manual da Febraban.

![photo5131982914081368079](https://user-images.githubusercontent.com/3595132/52956049-03388b80-336d-11e9-8681-cb5dda0202ef.jpg)

No br_boleto a codificação da espécie do titulo está da seguinte forma:

![photo5131982914081368080](https://user-images.githubusercontent.com/3595132/52956090-219e8700-336d-11e9-8f3e-abd6d835efc2.jpg)

![image](https://user-images.githubusercontent.com/3595132/52956301-9d98cf00-336d-11e9-9bbf-fa6562286041.png)

https://github.com/Trust-Code/odoo-brasil/blob/80ef42ce3760dc3ea739500703425c509fdd07f9/br_boleto/models/payment_mode.py#L33

https://github.com/Trust-Code/odoo-brasil/blob/80ef42ce3760dc3ea739500703425c509fdd07f9/br_boleto/boleto/document.py#L21

**Comment by marcelsavegnago** [comment]
Verifiquei que este tipo de situação é tratado no cnab de alguns bancos conforme codigo abaixo.
https://github.com/Trust-Code/odoo-brasil/blob/80ef42ce3760dc3ea739500703425c509fdd07f9/br_cnab/febraban/cnab_240/bancos/sicredi.py#L46

**Comment by marcelsavegnago** [comment]
Sugiro alteração no seguinte arquivo.

_especie_titulo_banco_

br_cnab/febraban/cnab_240/bancos/banco_brasil.py

```
    def _prepare_segmento(self, line):
        vals = super(BancoBrasil240, self)._prepare_segmento(line)
        vals['codigo_convenio_banco'] = self.format_codigo_convenio_banco(
            line.payment_mode_id)
        vals['carteira_numero'] = int(line.payment_mode_id.boleto_carteira[:2])
        vals['nosso_numero'] = self.format_nosso_numero(
            line.payment_mode_id.boleto_cnab_code, line.nosso_numero)
        vals['prazo_baixa'] = '0'
        vals['controlecob_numero'] = self.order.id
        vals['controlecob_data_gravacao'] = self.data_hoje()
        # Codigo juro mora:
        # 1 - Ao dia
        # 2 - Mensal
        # 3 - Isento (deve ser cadastrado no banco)
        vals['juros_cod_mora'] = 2
        # Banco do Brasil aceita apenas código de protesto 1, 2, ou
        # 3 (dias corridos, dias úteis ou não protestar, respectivamente)
        if vals['codigo_protesto'] not in [1, 2, 3]:
            vals['codigo_protesto'] = 3
        vals['cobranca_emissaoBloqueto'] = 2
        
        especie_titulo_banco = {'01':2, '02':12, '03':16, '04':21, '05':17, '06':99, '07':99, '08':4, '09':7, '13':19, '15':24, '16':30, '17':99, '99':99,}
        especie_titulo = especie_titulo_banco[line.payment_mode_id.boleto_especie]
        vals['especie_titulo'] = especie_titulo
       
 return vals
```

**Comment by danimaribeiro** [comment]
Envia um Pull Request.

**Comment by marcelsavegnago** [comment]
Blzz.. vou preparar aqui e envio.
