### ISSUE TITLE
erro ao criar posição fiscal

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#77]
quando tento criar uma posição fiscal aparece a mensagem abaixo

Odoo Aviso - Erro de Validação
Error while validating constraint

column account_fiscal_position.account_id does not exist
LINE 1: SELECT "account_fiscal_position"."account_id" as "account_i...
^

**Comment by danimaribeiro** [comment]
Atualize o módulo br_account.

**Comment by ewertonmagalhaes** [comment]
após fazer a atualização começou a dar problema no módulo contábil

ValueError: O campo `metodo_pagamento` n\xe3o existe

Contexto de erro:
Veja `account.journal.form`
[view_id: 447, xml_id: account.view_account_journal_form, model: account.journal, parent_id: n/a]

**Comment by danimaribeiro** [comment]
Remova o módulo br_point_sale, não está pronto para ser instalado ainda.
