### ISSUE TITLE
Cadastro de Produto

### ISSUE THREAD

**Issue by leandrocunha01** [Trust-Code/odoo-brasil#783]
No  odoo 12 não consigo cadastrar um produto, quando tento, aparece uma mensagem dizendo que NCM é obrigatório, porém não acho a aba fiscal nem o campo de cadastro do NCM,

**Comment by mliell** [comment]
Estou com a mesma situação.

**Comment by danimaribeiro** [comment]
![Screenshot (18)](https://user-images.githubusercontent.com/854781/55749338-0d930f80-5a17-11e9-8c91-cc54651edcd7.png)

**Comment by mliell** [comment]
Notei que a aba está invisível. Removendo, irá aparecer.

![odoo](https://user-images.githubusercontent.com/4391791/55753363-7c289b00-5a20-11e9-9065-39790626d67b.png)

**Comment by gledsoninformatica** [comment]
Onde preciso modificar para que a aba Contabilidade apareça por padrão ao entrar no produto? Estou com esse mesmo problema do campo NCM ficar oculto.

**Comment by danimaribeiro** [comment]
Você precisa ter a permissão maior relacionado a contabilidade.
Cadastro de usuários.

**Comment by gledsoninformatica** [comment]
Meu usuário já estava como permissão máxima em todos os módulos, mesmo assim a aba contabilidade só aparece executando o procedimento abaixo.

Se tiver mais alguma sugestão, agradeço !!
> 
> Notei que a aba está invisível. Removendo, irá aparecer.
> 
> ![odoo](https://user-images.githubusercontent.com/4391791/55753363-7c289b00-5a20-11e9-9065-39790626d67b.png)

**Comment by gledsoninformatica** [comment]
> No odoo 12 não consigo cadastrar um produto, quando tento, aparece uma mensagem dizendo que NCM é obrigatório, porém não acho a aba fiscal nem o campo de cadastro do NCM,

Boa noite, conseguiu essa questão do cadastro de produtos? Estou com o mesmo problema da aba Contabilidade oculta...

**Comment by katiakweb** [comment]
Também tenho este problema... conseguiram resolver?

**Comment by abrunos** [comment]
Vá em configurações e habilite o módulo desenvolvedor.
Após habilitar entre em cadastro do usuário e clica em permissão contábil.
Vai aparecer a aba contabilidade no cadastro do produto.

Se for um produto ou “consumível” precisa localizar o ncm.
Se for um serviço precisa localizar o código do serviço.

Pronto, tá resolvido o problema. 

Boa sorte!

**Comment by katiakweb** [comment]
@abrunos eu te amo cara! Obrigada por perder seu tempo comigo! Valeu mesmo! :smile:

**Comment by abrunos** [comment]
@katiakweb valeu!
