### ISSUE TITLE
Emissão Regime Normal PIS e COFINS

### ISSUE THREAD

**Issue by paulafernanda** [Trust-Code/odoo-brasil#79]
Na emissão Regime Normal para revenda de veículos, a base de cálculo do PIS e COFINS é sobre a diferença da venda entre a entrada e a saída da nota. Por isso o campo Base de Cálculo, deve estar aberto, para o usuário informar o valor.

**Comment by paulafernanda** [comment]
Danimar criei o ajuste fiscal nos arquivos para atender a legislação conforme segue:

http://tdn.totvs.com/pages/releaseview.action;jsessionid=3A8ACB1568B10DCCB1B12A074F25BDC1?pageId=185740883

Gostaria de saber como posso subir o código que implementei. 
Obs.: Precisa ser "polido", ou seja, criar casos de testes, seguir os padrões de estrutura de dados que vocês utilizam.

**Comment by danimaribeiro** [comment]
Me envia um Pull Request aqui.
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Assim que possível eu faço os ajustes para integrar.

**Comment by danimaribeiro** [comment]
Implementado https://github.com/Trust-Code/odoo-brasil/pull/216
