### ISSUE TITLE
Formação da Chave de NF-e substituindo mês por minuto.

### ISSUE THREAD

**Issue by Mibnet** [Trust-Code/odoo-brasil#797]
Há uma substituição na formação da chave de NFe do mês pelo minuto da emissão, o que posteriormente causa uma não autorização no cancelamento da nota.

https://github.com/Trust-Code/odoo-brasil/blob/7a1b34c25a9a8d530ac488c25deb6b0ff3edff53/br_nfe/models/invoice_eletronic.py#L872

Sugiro alteração para:
` 'emissao': self.data_emissao.strftime("%y%m"), `

Obrigado!

**Comment by danimaribeiro** [comment]
@marinaGD Verifica este por favor.
