### ISSUE TITLE
Erro ao instalar módulos do BR

### ISSUE THREAD

**Issue by izaguerreiro** [Trust-Code/odoo-brasil#80]
Bom dia, 

Segui o passo a passo http://www.trustcode.com.br/blog/seu-blog-1/post/instalando-o-odoo-10-3, para adicionar os módulos do BR ao Odoo, porém quando tento instalar da os seguintes erros:
No module named pytrustnfe.nfe

Porém o módulo está instalado.

**Comment by danimaribeiro** [comment]
O comando a seguir executa normalmente?
python -c "import pytrustnfe.nfe"

**Comment by izaguerreiro** [comment]
Funcionou, no shell do Python eu consigo importar o pytrustnfe.nfe normalmente também.

**Comment by TecSecret** [comment]
Instala essas dependências do pip.
sudo pip install pytrustnfe
sudo  pip install python-boleto
sudo pip install python-cnab
sudo pip install PyTrustNFe

**Comment by izaguerreiro** [comment]
Consegui instalar, acho que foi algum tipo de cache. Reiniciei o navegador e ai consegui instalar corretamente.
Muito obrigada pela ajuda!
