### ISSUE TITLE
Dúvida sobre AGPL

### ISSUE THREAD

**Issue by fmluizao** [Trust-Code/odoo-brasil#800]
Olá,

Estou com algumas dúvidas sobre a licença AGPL, mais relacionada à questão legal, copyright e tal.

Vamos supor que eu queira instalar o odoo em uma determinada empresa.

Instalo o odoo + odoo-brasil, e desenvolvo alguns módulos específicos só para antender a empresa.

Fazendo isso, tenho que disponibilizar o código dos módulos feitos sob medida para a empresa?

Ou só tenho que publicar o código quando alterar alguma coisa no odoo/odoo-brasil?

Pelo que entendi lendo por aí, seria considerado um trabalho "derivado", mesmo não tendo alterado o código original, logo teria que publicar o código.

Estou correto?

**Comment by danimaribeiro** [comment]
Basicamente se você tiver usuários do seu software e eles solicitarem o código você tem que disponibilizar, então no caso de usar para uma empresa só não é necessário somente eles serão seus usuários então somente eles precisam ter acesso ao software.
Caso você crie um serviço SaaS cada usuário terá direito ao código fonte.
