### ISSUE TITLE
emissão de NFe de entrada

### ISSUE THREAD

**Issue by ewertonmagalhaes** [Trust-Code/odoo-brasil#81]
como emitir NFe de entrada? na versão 8 havia o modulo de importação, como é o procedimento para versão 10, algum tutorial?

**Comment by danimaribeiro** [comment]
Fatura de Fornecedor -> Criar novo.

**Comment by ewertonmagalhaes** [comment]
sim...criei a fatura de fornecedor mas não me aparece nenhuma opção de criar NF .

**Comment by danimaribeiro** [comment]
Campo "Emitente", usar emissão própria.
