### ISSUE TITLE
Ginfes - Erro E208 Valor do ISS não pode ser superior a R$ 0,00 (zero) ...

### ISSUE THREAD

**Issue by marcelsavegnago** [Trust-Code/odoo-brasil#826]
Sobre a mensagem de erro:
 **E208 - Valor do ISS não pode ser superior a R$ 0,00 (zero) quando o contribuinte for optante do simples nacional e não tiver ISS retido na fonte (GINFES)**. 

Tem alguma tratativa para este caso? Eu fiz um teste selecionando uma alíquota de ISS com o percentual ZERADO e com isso a TAG de base de calculo do ISS (obrigatório) vai para o XML e a NFSe foi aceita pelo GINFES.  

Porém, segundo contador a alíquota de 2% (neste caso) deve ser informada no XML e preenchida na NFS. 

A pergunta tem apenas como objetivo evitar algum PR desnecessário. 

Abraços,

**Comment by danimaribeiro** [comment]
Acho que o contador está errado, se é simples nacional vc não paga ISS diretamente, você paga a alíquota do Simples.

**Comment by marcelsavegnago** [comment]
Então nem tem que sair alíquota na NFSe e nem no xml certo?  Não vejo sentido informar uma alíquota que não será usada para nada.
