### ISSUE TITLE
Situação: 610 Mensagem: Rejeicao: Total da NF difere do somatorio dos Valores compoe o valor Total da NF.

### ISSUE THREAD

**Issue by Alexandre-Bernardes** [Trust-Code/odoo-brasil#847]
Baixei e atualizei ontem o módulo e passei a obter esse erro:

"Situação: 610
Mensagem: Rejeicao: Total da NF difere do somatorio dos Valores compoe o valor Total da NF."

Ao checar o xml a tag <vNF> possui valor ZERO.
Trata-se de emissão de NFe com emitente no simples nacional.

Alguma idéia do que pode ser??

**Comment by danimaribeiro** [comment]
Você está configurando de maneira errada o imposto na linha da fatura.
Para o simples nacional você não deve colocar Alíquota.

**Comment by Alexandre-Bernardes** [comment]
Obrigado pela atenção,
mas as alíquotas estão zeradas, temum unico item na nota, e o total da NFe permace como zero.
Se tiver mais alguma sugestão eu agradeço muito.
Continuo examinando aqui.
Obrigado

**Comment by danimaribeiro** [comment]
"Para o simples nacional você não deve colocar Alíquota."

**Comment by Alexandre-Bernardes** [comment]
MAS EU NÃO COLOQUEI!
Tá tudo com zero por default.
devo limpar os campos então pra ficar em branco, isso???
vou tentar então

**Comment by kcarriello** [comment]
Estou com o mesmo erro, mesmo com as alíquotas todas zeradas
