### ISSUE TITLE
Erro Responsavel Técnico

### ISSUE THREAD

**Issue by zztecnet** [Trust-Code/odoo-brasil#868]
Bom dia, atualizei os módulos da localização da versão 11.0 do Odoo para incluir o Responsavel técnico que já é obrigatorio em alguns Estados(PE). Coneguimos sinalizar no cadastro quem é  o reponsavel tecnico. Mas na hora de transmitir a NF-e continua com o erro: Situação: 972
Mensagem: Rejeição: Obrigatória as informações do responsável técnico
As tags do infRespTec não são adicionadas ao XML da nota. Poderiam ajudar?

**Comment by ImplantiSolucoes** [comment]
Como esta a configuração do odoo ?

**Comment by zztecnet** [comment]
Boa tarde, está na versão 11.00 com Pytrustnfe 1.0.6. 
Na configuração da empresa selecionamos a o própira empresa como responsavel técnico para fins de testes. Mo XML da nota a enviar as não constam as tags infresptec.

**Comment by ImplantiSolucoes** [comment]
para que tudo funciona é necessário o Pytrustnfe 1.0.35+

**Comment by zztecnet** [comment]
Bom dia, seria o Pytrustnfe3? Estamos utilizando pytrusnfe 1.0.6. Teoricamente ela é mais recente pois foi lançada em julho/19.

**Comment by ImplantiSolucoes** [comment]
isso Pytrustnfe3

**Comment by zztecnet** [comment]
Funcionou. Obrigado. 
Uma última coisa: você já testou a emissão de Nfe onde o PIS é arredondado? Por ex.: r$10,00. A duplicata sai com valor 1 centavo maior o que causa erro na sefaz.

**Comment by ImplantiSolucoes** [comment]
isso é um caso de legislação ou ta saindo com valor arredondado ?

**Comment by zztecnet** [comment]
Sai com valor arredondado na duplicata. Ele arredonda no PIS por legislação  que no caso dá  r$0,07 e ocorre normalmente. Mas o valor da duplicata deveria sair r$10,00( Valor da nota) mas como houve o arredondamento do PIS soma 1 centavo dando r$10,01 gerando a rejeição na sefaz

**Comment by ImplantiSolucoes** [comment]
Posta um xml no pastebin e vamos dar uma analisada

**Comment by ImplantiSolucoes** [comment]
Acho que é o caso do @danimaribeiro fechar esse aki, já foi resolvido

**Comment by danimar-nextroll** [comment]
@ImplantiSolucoes Sim, ja foi resolvido.
