### ISSUE TITLE
Diretório para salvar XMLs

### ISSUE THREAD

**Issue by rodriguesraphael** [Trust-Code/odoo-brasil#88]
Em qual diretório os xmls dos documentos eletrônicos são salvos?
Na versão 8.0 havia dois campos no cadastro da empresa para informar os diretórios,
procurei e não encontrei.

**Comment by martini97** [comment]
No arquivo de configurações de odoo (odoo.conf) existe uma tag data_dir, que indica uma pasta no sistema, dentro dela existe uma outra pasta chamada filestore, e dentro dela existirão algumas pastas com os nomes dos bancos de dados, dentro de cada uma dessas pastas estarão os arquivos gerados pelo sistema.

**Comment by rodriguesraphael** [comment]
Entendi Alessandro.
Eu preciso apenas criar uma pasta e defini-la no arquivo config do odoo. E
as outras pastas o sistema cria então!? É isto. Obrigado desde já.

Em seg, 23 de jan de 2017 12:48, Alessandro Martini <
notifications@github.com> escreveu:

**Comment by danimaribeiro** [comment]
Isso.
