### ISSUE TITLE
Regerar campo xml_to_send

### ISSUE THREAD

**Issue by gabrielcontessotto** [Trust-Code/odoo-brasil#904]
Olá a todos, 

Como posso regerar o campo xml_to_send, quanto habilito a edição da Nfe, e edito a nota fiscal esse arquivo que é enviado a Fisco não é atualizando sempre enviando o modelo de nota anterior. 

Por exemplo tinha uma nota numero 2279 e por acaso preciso que ela seja o numero 2285. 

Eu edito a nota, 'Habilitar edição' e mudo o valor do campo. 

Mesmo depois que faço isso o valor permanece o mesmo. 

Odoo 11

**Comment by gabrielcontessotto** [comment]
Fiz a seguinte alteração no sistema: 

Como minha Nota Fiscal é conjugada trabalhei nos módulos, _br_nfe_ e _br_nfse_ginfes_

No modulo _**br_nfe**_ vá até o arquivo, _models/invoice_eletronic_item.py_

Aproximadamente na linha 885, inseri o seguinte código. 

`   @api.multi

    def action_back_to_draft(self):

        self.state = 'draft'

        InvoiceEletronic.action_post_validate(self)`

E no módulo _**br_nfse_ginfes**_ vá até o arquivo,  _models/invoice_eletronic_item.py_

Aproximadamente na linha 208 adicionei o seguinte trecho de código

`   @api.multi

    def action_back_to_draft(self):

        self.state = 'draft'

        InvoiceEletronic.action_post_validate(self)`

Explicação longa, existe uma opção no sistema que é a edição da nota fiscal, depois quando vc edita a nota ela não atualiza os dados do xml o banco de dados fica perfeito com os dados corretos  mas a nota em si não (xml). 

O que fiz, depois que eu edito a nota eu reexcuto a regereção da nota fiscal gerando um novo xml com os dados agora inserios.

**Comment by danimaribeiro** [comment]
Este foi corrigido há algum tempo já:
https://github.com/Trust-Code/odoo-brasil/pull/849

**Comment by gabrielcontessotto** [comment]
@danimaribeiro, obrigado pela resposta :) 

Vou atualizar os meus modulos :)
