### ISSUE TITLE
[12.0] Contas de Dedução de Receita (Impostos)

### ISSUE THREAD

**Issue by marcelsavegnago** [Trust-Code/odoo-brasil#919]
Boa tarde. 

Na localização da Trustcode é criado a conta de dedução de receita e despesa. Porém, quanto gero uma invoice que lança um crédito como ICMS a recolher e lança um débito na conta de dedução (-) ICMS. Com isso, nenhum relatório que traz o saldo ou apura os impostos funciona (OCA e Relatório de Impostos Odoo S.A. Enterprise)

Percebi que, o que amarra os lançamentos é o campo Imposto Originador na linha do lançamento do diário. Os relatórios acabam trazendo as duas contas e com isso zerando já que uma é débito e a outra é crédito.

Fiz um teste zerando este campo na linha da conta de dedução de receita "(-) ICMS" e rodou legal

Como esta conta de dedução vem da localização da Trustcode, vocês acreditam que seja possível para não preencher este campo Imposto Originador na linha de da conta de dedução? Tem alguma dica do que pode ser feito e onde?

Funcionamento Atual:
![image](https://user-images.githubusercontent.com/3595132/69371239-36060c00-0c7e-11ea-9913-f3d4ddf9c8b6.png)
![image](https://user-images.githubusercontent.com/3595132/69371673-115e6400-0c7f-11ea-9303-8af8160691a3.png)

Funcionamento Sugerido:
![image](https://user-images.githubusercontent.com/3595132/69371111-f17a7080-0c7d-11ea-8123-bb3addba3685.png)
![image](https://user-images.githubusercontent.com/3595132/69371713-2935e800-0c7f-11ea-90b6-d4446db8dcba.png)

**Comment by danimaribeiro** [comment]
Talvez esse? 
https://github.com/Trust-Code/odoo-brasil/blob/12.0/br_account/models/account_invoice.py#L362

**Comment by marcelsavegnago** [comment]
> Talvez esse?
> https://github.com/Trust-Code/odoo-brasil/blob/12.0/br_account/models/account_invoice.py#L362

Deu certo. Obrigado.

Submeti uma PR tanto para versão 11 como para a 12.
https://github.com/Trust-Code/odoo-brasil/pull/921
https://github.com/Trust-Code/odoo-brasil/pull/922
