### ISSUE TITLE
MDF-E+ODOO 13

### ISSUE THREAD

**Issue by ghost** [Trust-Code/odoo-brasil#933]
Boa noite

Gostaria de saber, onde encontro para baixar esse app para emissão de manifesto  eletrônico MDF? Instalei alguns mais sempre falta dependencia
Obrigado

**Comment by ghost** [comment]
Alguém?

**Comment by ghost** [comment]
Bom dia, não existe algum aqui nesse forum??? rs

**Comment by danimaribeiro** [comment]
Bom dia, aqui não é fórum de perguntas.
Aqui sim:
https://help.odoo-next.com.br/

Não existe esse módulo que você quer.

**Comment by ghost** [comment]
Bom dia amigo

 

Obrigado por responder

 

Sim amigo, em nemhuma versão do Odoo (OPENERP), não exite emissoa de Manifesto, somente NFE?

 

Obrigado

 

De: Danimar Ribeiro [mailto:notifications@github.com] 
Enviada em: segunda-feira, 13 de janeiro de 2020 11:45
Para: Trust-Code/odoo-brasil
Cc: JKinfonet; Author
Assunto: Re: [Trust-Code/odoo-brasil] MDF-E+ODOO 13 (#933)

 

Bom dia, aqui não é fórum de perguntas.
Aqui sim:
https://help.odoo-next.com.br/

Não existe esse módulo que você quer.
