### ISSUE TITLE
[12.0] Rejeição: Não informada vBCSTRet, pST, vICMSSubstituto e vICMSSTRet

### ISSUE THREAD

**Issue by juniorcastru** [Trust-Code/odoo-brasil#941]
Olá pessoal! Tudo bem com vocês?

Alguém já se deparou com este cenário?

**Faturamento NFe na versão 12.**

Neste exemplo a venda é de SP - Regime Normal para SP - Regime Normal, utilizando o CFOP 5405 e o CST 60. 

**Mensagem do aplicativo**

Situação: 938
Mensagem: Rejeição: Não informada vBCSTRet, pST, vICMSSubstituto e vICMSSTRet [nItem: 1]

Sempre que emitido uma NF-e para operações que não sejam consumidor final e informado CST 60 ou CSOSN 500 é obrigatório o preenchimento dos campos vBCSTRet, pST, vICMSSubstituto e vICMSSTRet.
Implementação opcional a critério da UF.

**Regra de Validação da Sefaz**

Nota Técnica 2018.005 - v 1.20 - http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=j/im9zMlcIE=

Obrigado.

**Comment by danimaribeiro** [comment]
Adicionado os campos para este caso.
