### ISSUE TITLE
Fatura e NFe para Amostras ou Brindes

### ISSUE THREAD

**Issue by jonatasartur** [Trust-Code/odoo-brasil#953]
Alguém já utilizou os sistema da TrustCode para enviar Amostras ou Brindes e gerar NFe?

**Objetivo:**
Tenho um produto que vendo normalmente, e preciso enviar esse mesmo produto como amostra. Gerando uma Ordem de Venda, Saída de Estoque, Fatura e NFe.
Na NFe o valor precisa ser especificado, e para isso preciso especificar o valor na Ordem de Venda.

Se alguém já faz esse procedimento ou tiver uma sugestão de como fazer essa operação. :smile: 

**Problema:**

1. Na NFe é preenchido a Fatura, porém precisava que esse campo viesse vazio ou zerado.
![20200313001](https://user-images.githubusercontent.com/15130449/76660844-a0f29000-6558-11ea-9913-7f556757be30.png)

2. Na Ordem é criado uma Fatura, e o cliente fica devendo esse valor, porém é uma amostra sem custo para o cliente. Precisava que não gerasse uma fatura ou ela fosse zerado.
![20200313002](https://user-images.githubusercontent.com/15130449/76661218-9f759780-6559-11ea-9060-5a1fd1409f19.png)

**Comment by danimaribeiro** [comment]
Use o mapeamento de contas na posição fiscal para usar contas que não geram contas a receber.

**Comment by jonatasartur** [comment]
> Use o mapeamento de contas na posição fiscal para usar contas que não geram contas a receber.

Realmente havia esquecido dessa opção. Arrumei o Plano de Conta e ficou certinho! Muito obrigado. :smile: 

Quanto a Fatura e Duplicata na NFe, fiz um modo de pagamento "90 - Sem pagamento", porém o XML sempre é gerado com a opção "01 - Dinheiro".
Olhando por cima achei estranho essa condição na [invoice_eletronic](https://github.com/Trust-Code/odoo-brasil/blob/e1c86844390ed77aba663f819682295364049880/br_nfe/models/invoice_eletronic.py#L806), está sempre preenchendo a tPag com 01, ainda não tive tempo de olhar com calma.
```
 if len(duplicatas) > 0 and\
                self.fiscal_position_id.finalidade_emissao not in ('2', '4'):
            vals['cobr'] = cobr
            pag['tPag'] = '01' if pag['tPag'] == '90' else pag['tPag']
            pag['vPag'] = "%.02f" % self.valor_final
```

**Comment by jonatasartur** [comment]
Não sei se é o certo ou a melhor opção, mas alterei a condição, e inclui para verificar a condição de pagamento, e funcionou.
Se estiver errado, estou aberto a sugestões. :grin: 
```
if len(duplicatas) > 0 and\
		self.fiscal_position_id.finalidade_emissao not in ('2', '4') and\
		self.payment_mode_id.tipo_pagamento != '90':
	vals['cobr'] = cobr
	pag['tPag'] = '01' if pag['tPag'] == '' else pag['tPag']
	pag['vPag'] = "%.02f" % self.valor_final
```
