### ISSUE TITLE
ReactJS

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [Trust-Code/odoo-brasil#972]
É viável melhorar a UX do Odoo com reactjs? Tenho interesse em implementar interfaces em reactjs no Odoo. Tem algum caminho das pedras?

**Comment by danimaribeiro** [comment]
Tu vai ter que aprender o framework js do proprio Odoo pra isso.

Se tu diz a parte web do Odoo, dai sim tu pode usar qualquer framework javascript.
