### ISSUE TITLE
Qual versão do odoo escolher

### ISSUE THREAD

**Issue by linchiyu** [Trust-Code/odoo-brasil#978]
Olá! 

Gostaria de saber qual a versão do Odoo que vocês recomendam a instalação. Quero apenas utilizar os recursos do ERP e vi que tem vários apps da Trust code que iriam ajudar bastante.
Eu vi que a versão 13 ainda está muito nova e sem muitos apps no momento. Então fiquei na dúvida entre o 11, 11.1 ou o 12.

Qual vocês recomendam?

**Comment by danimaribeiro** [comment]
Nas próximas semanas vou publicar o resto dos módulos da 13.0.
Minha recomendação é sempre usar a última versão, mas os nossos módulos são compatíveis entre todas as versões basicamente.

**Comment by linchiyu** [comment]
Obrigado pela resposta, acabei instalando a versão 11 mesmo. 
Vou estar acompanhando a publicação dos módulos da 13.0.
