### ISSUE TITLE
Addon Faturamento

### ISSUE THREAD

**Issue by brunomrosa** [Trust-Code/odoo-brasil#979]
Só é possível utilizar o Odoo Brasil com o módulo de Faturamento da versão do Odoo Enterprise?

Por exemplo esse módulo feito para o community: https://apps.odoo.com/apps/modules/13.0/om_account_accountant/

**Comment by danimaribeiro** [comment]
Aqui estão todos os módulos.

https://github.com/Trust-Code/odoo-brasil/tree/12.0

Versão 13.0 está saindo daqui uns dias, só preciso ajustar a licença dos módulos ainda.
