### ISSUE TITLE
Erro ao definir o plano de contas

### ISSUE THREAD

**Issue by izaguerreiro** [Trust-Code/odoo-brasil#98]
Bom dia, 

Quando tento salvar um modelo de plano de contas em Contabilidade > Configurações.
O sistema não salva a alteração e ocorre o erro abaixo:

TypeError: this.$buttons.off(...).destroy is not a function

http://127.0.0.1:8069/web/content/433-5dda2de/web.assets_backend.js:2971
Traceback:
ChatAction<.destroy@http://127.0.0.1:8069/web/content/433-5dda2de/web.assets_backend.js:2971:850
OdooClass.extend/</prototype[name]</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:3009:556
WidgetAction<.destroy@http://127.0.0.1:8069/web/content/433-5dda2de/web.assets_backend.js:1622:320
ActionManager<.clear_action_stack/<@http://127.0.0.1:8069/web/content/433-5dda2de/web.assets_backend.js:1635:212
_.collect@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:13:270
ActionManager<.clear_action_stack@http://127.0.0.1:8069/web/content/433-5dda2de/web.assets_backend.js:1635:157
ActionManager<.push_action/<@http://127.0.0.1:8069/web/content/433-5dda2de/web.assets_backend.js:1629:135
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.when/updateFunc/<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:549:482
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.add@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:542:467
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:753
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.when/updateFunc/<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:549:482
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:548:31
ViewManager<.search/</<@http://127.0.0.1:8069/web/content/433-5dda2de/web.assets_backend.js:1707:90
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:678
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:548:31
DropMisordered<.add/<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:3217:259
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:548:31
DropMisordered<.add/<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:3217:259
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/</deferred[tuple[0]]@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:548:31
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
.Deferred/promise.then/</</<@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:547:849
jQuery.Callbacks/fire@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:541:281
jQuery.Callbacks/self.fireWith@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:546:198
done@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:937:86
.send/callback@http://127.0.0.1:8069/web/content/307-49e0f13/web.assets_common.js:957:15

**Comment by crsilveira** [comment]
Não parei pra resolver o problema ainda, e também não sei pq acontece, mas Ativando o Modo Desenvolvedor, acho q vc consegue, ou Activate the developer mode (with assets)

**Comment by izaguerreiro** [comment]
Tentei salvar com o modo desenvolvedor ativado, o erro não apareceu, porém não salvou o modelo de plano de contas.

**Comment by danimaribeiro** [comment]
O modelo de plano de contas você consegue salvar apenas uma vez.
É uma base de dados nova?

**Comment by izaguerreiro** [comment]
Sim, é uma base nova.
Instalei seguindo o link de um passo-a-passo que você me enviou.

**Comment by danimaribeiro** [comment]
Alguém consegue um vídeo do problema?

**Comment by izaguerreiro** [comment]
Me passa seu e-mail para eu te enviar o video.

**Comment by danimaribeiro** [comment]
danimaribeiro@gmail.com


Em 9 de mar de 2017 2:40 PM, "Izabela Guerreiro" <notifications@github.com>
escreveu:
